const highPres_CBP_CCS = [
    {ModelId:"BP", Data:[
        {ValveType:{ Value : "Balanced Piston| Direct Spring-Op", Condition : [{MD:"BP5"} ]}},{SafetyRelief:{ Value : "Safety Relief", Condition : [{MD:"BP5"} ]}},{Balanced:{ Value : "Yes", Condition : [{MD:"BP5"} ]}},{Nozzle:{ Value : "Full", Condition : [{MD:"BP5"} ]}},{Bonnet:{ Value : "Vented", Condition : [{MD:"BP5"} ]}},
        {ValveType:{ Value : "Balanced Piston| Direct Spring-Op", Condition : [{MD:"BP6"} ]}},{SafetyRelief:{ Value : "Safety Relief", Condition : [{MD:"BP6"} ]}},{Balanced:{ Value : "Yes", Condition : [{MD:"BP6"} ]}},{Nozzle:{ Value : "Full", Condition : [{MD:"BP6"} ]}},{Bonnet:{ Value : "Vented", Condition : [{MD:"BP6"} ]}},
        {InletSize:{ Value : "1/2", Condition : [{CS:"0"} ]}},{OutletSize:{ Value : "1", Condition : [{CS:"0"} ]}},
        {InletSize:{ Value : "3/4", Condition : [{CS:"1"} ]}},{OutletSize:{ Value : "1", Condition : [{CS:"1"} ]}},
        {InletSize:{ Value : "1", Condition : [{CS:"2"} ]}},{OutletSize:{ Value : "1", Condition : [{CS:"2"} ]}},
        {InletSize:{ Value : "1", Condition : [{CS:"3"} ]}},{OutletSize:{ Value : "1.5", Condition : [{CS:"3"} ]}},
        {InletSize:{ Value : "1 1/2", Condition : [{CS:"4"} ]}},{OutletSize:{ Value : "1 1/2", Condition : [{CS:"4"} ]}},
        {InletSize:{ Value : "1 1/2", Condition : [{CS:"5"} ]}},{OutletSize:{ Value : "2", Condition : [{CS:"5"} ]}},
        {InletSize:{ Value : "2", Condition : [{CS:"6"} ]}},{OutletSize:{ Value : "2", Condition : [{CS:"6"} ]}},
        {InletSize:{ Value : "1 1/2", Condition : [{CS:"7"} ]}},{OutletSize:{ Value : "2 1/2", Condition : [{CS:"7"} ]}},
        {InletConn:{ Value : "Thrd.", Condition : [{VC:"M"} ]}},{InletFinish:{ Value : "MNPT", Condition : [{VC:"M"} ]}},{OutletConn:{ Value : "Thrd.", Condition : [{VC:"M"} ]}},{OutletFinish:{ Value : "FNPT", Condition : [{VC:"M"} ]}},{Standard:{ Value : "ASME B1.20.1", Condition : [{VC:"M"} ]}},
        {InletConn:{ Value : "Thrd.", Condition : [{VC:"F"} ]}},{InletFinish:{ Value : "FNPT", Condition : [{VC:"F"} ]}},{OutletConn:{ Value : "Thrd.", Condition : [{VC:"F"} ]}},{OutletFinish:{ Value : "FNPT", Condition : [{VC:"F"} ]}},{Standard:{ Value : "ASME B1.20.1", Condition : [{VC:"F"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{VC:"1"} ]}},{InletRating:{ Value : "150#", Condition : [{VC:"1"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{VC:"1"} ]}},{OutletRating:{ Value : "150#", Condition : [{VC:"1"} ]}},{Standard:{ Value : "ASME B16.5", Condition : [{VC:"1"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{VC:"2"} ]}},{InletRating:{ Value : "300#", Condition : [{VC:"2"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{VC:"2"} ]}},{OutletRating:{ Value : "150#", Condition : [{VC:"2"} ]}},{Standard:{ Value : "ASME B16.5", Condition : [{VC:"2"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{VC:"A"} ]}},{InletRating:{ Value : "300#", Condition : [{VC:"A"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{VC:"A"} ]}},{OutletRating:{ Value : "300#", Condition : [{VC:"A"} ]}},{Standard:{ Value : "ASME B16.5", Condition : [{VC:"A"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{VC:"3"} ]}},{InletRating:{ Value : "600#", Condition : [{VC:"3"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{VC:"3"} ]}},{OutletRating:{ Value : "150#", Condition : [{VC:"3"} ]}},{Standard:{ Value : "ASME B16.5", Condition : [{VC:"3"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{VC:"B"} ]}},{InletRating:{ Value : "600#", Condition : [{VC:"B"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{VC:"B"} ]}},{OutletRating:{ Value : "300#", Condition : [{VC:"B"} ]}},{Standard:{ Value : "ASME B16.5", Condition : [{VC:"B"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{VC:"4"} ]}},{InletRating:{ Value : "1500#", Condition : [{VC:"4"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{VC:"4"} ]}},{OutletRating:{ Value : "300#", Condition : [{VC:"4"} ]}},{Standard:{ Value : "ASME B16.5", Condition : [{VC:"4"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{VC:"5"} ]}},{InletRating:{ Value : "2500#", Condition : [{VC:"5"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{VC:"5"} ]}},{OutletRating:{ Value : "300#", Condition : [{VC:"5"} ]}},{Standard:{ Value : "ASME B16.5", Condition : [{VC:"5"} ]}},
        {InletConn:{ Value : "Welded", Condition : [{VC:"8"} ]}},{InletFinish:{ Value : "Male SW", Condition : [{VC:"8"} ]}},{OutletConn:{ Value : "Welded", Condition : [{VC:"8"} ]}},{OutletFinish:{ Value : "Male SW", Condition : [{VC:"8"} ]}},
        {InletConn:{ Value : "Thrd.", Condition : [{VC:"9"} ]}},{InletFinish:{ Value : "MNPT", Condition : [{VC:"9"} ]}},{OutletConn:{ Value : "Thrd.", Condition : [{VC:"9"} ]}},{OutletFinish:{ Value : "FNPT", Condition : [{VC:"9"} ]}},{Standard:{ Value : "ASME B1.20.1", Condition : [{VC:"9"} ]}},
        {Base:{ Value : "316 SST", Condition : [{BT:"0"} ]}},{Disc:{ Value : "316 SST", Condition : [{BT:"0"} ]}},{Guide:{ Value : "316 SST", Condition : [{BT:"0"} ]}},{Spring:{ Value : "17-7 PH SST", Condition : [{BT:"0"} ]}},
        {Base:{ Value : "316 SST", Condition : [{BT:"1"} ]}},{Disc:{ Value : "316 SST", Condition : [{BT:"1"} ]}},{Guide:{ Value : "316 SST", Condition : [{BT:"1"} ]}},{Spring:{ Value : "316 SST", Condition : [{BT:"1"} ]}},
        {Base:{ Value : "316 SST", Condition : [{BT:"2"} ]}},{Disc:{ Value : "316 SST", Condition : [{BT:"2"} ]}},{Guide:{ Value : "316 SST", Condition : [{BT:"2"} ]}},{Spring:{ Value : "Inconel® X750", Condition : [{BT:"2"} ]}},
        {Base:{ Value : "Monel®", Condition : [{BT:"3"} ]}},{Disc:{ Value : "Monel®", Condition : [{BT:"3"} ]}},{Guide:{ Value : "Monel®", Condition : [{BT:"3"} ]}},{Spring:{ Value : "Inconel® X750", Condition : [{BT:"3"} ]}},
        {Base:{ Value : "Monel®", Condition : [{BT:"4"} ]}},{Disc:{ Value : "Monel®", Condition : [{BT:"4"} ]}},{Guide:{ Value : "Monel®", Condition : [{BT:"4"} ]}},{Spring:{ Value : "Inconel® X750", Condition : [{BT:"4"} ]}},
        {Base:{ Value : "Hastelloy® C", Condition : [{BT:"5"} ]}},{Disc:{ Value : "Hastelloy® C", Condition : [{BT:"5"} ]}},{Guide:{ Value : "Hastelloy® C", Condition : [{BT:"5"} ]}},{Spring:{ Value : "Inconel® X750", Condition : [{BT:"5"} ]}},
        {Base:{ Value : "Hastelloy® C", Condition : [{BT:"6"} ]}},{Disc:{ Value : "Hastelloy® C", Condition : [{BT:"6"} ]}},{Guide:{ Value : "Hastelloy® C", Condition : [{BT:"6"} ]}},{Spring:{ Value : "Hastelloy® C", Condition : [{BT:"6"} ]}},
        {Base:{ Value : "316 SST", Condition : [{BT:"7"} ]}},{Disc:{ Value : "316 SST", Condition : [{BT:"7"} ]}},{Guide:{ Value : "316 SST", Condition : [{BT:"7"} ]}},{Spring:{ Value : "Inconel® X750", Condition : [{BT:"7"} ]}},
        {Base:{ Value : "316 SST", Condition : [{BT:"A"} ]}},{Disc:{ Value : "316 SST", Condition : [{BT:"A"} ]}},{Guide:{ Value : "316 SST", Condition : [{BT:"A"} ]}},{Spring:{ Value : "MP-35N", Condition : [{BT:"A"} ]}},
        {Base:{ Value : "316 SST", Condition : [{BT:"B"} ]}},{Disc:{ Value : "316 SST", Condition : [{BT:"B"} ]}},{Guide:{ Value : "316 SST", Condition : [{BT:"B"} ]}},{Spring:{ Value : "MP-35N", Condition : [{BT:"B"} ]}},
        {Base:{ Value : "Monel®", Condition : [{BT:"C"} ]}},{Disc:{ Value : "Monel®", Condition : [{BT:"C"} ]}},{Guide:{ Value : "Monel®", Condition : [{BT:"C"} ]}},{Spring:{ Value : "MP-35N", Condition : [{BT:"C"} ]}},
        {Base:{ Value : "Monel®", Condition : [{BT:"D"} ]}},{Disc:{ Value : "Monel®", Condition : [{BT:"D"} ]}},{Guide:{ Value : "Monel®", Condition : [{BT:"D"} ]}},{Spring:{ Value : "MP-35N", Condition : [{BT:"D"} ]}},
        {Base:{ Value : "Hastelloy® C", Condition : [{BT:"E"} ]}},{Disc:{ Value : "Hastelloy® C", Condition : [{BT:"E"} ]}},{Guide:{ Value : "Hastelloy® C", Condition : [{BT:"E"} ]}},{Spring:{ Value : "MP-35N", Condition : [{BT:"E"} ]}},
        {Base:{ Value : "Hastelloy® C", Condition : [{BT:"F"} ]}},{Disc:{ Value : "Hastelloy® C", Condition : [{BT:"F"} ]}},{Guide:{ Value : "Hastelloy® C", Condition : [{BT:"F"} ]}},{Spring:{ Value : "MP-35N", Condition : [{BT:"F"} ]}},
        {Base:{ Value : "Duplex", Condition : [{BT:"G"} ]}},{Disc:{ Value : "Duplex", Condition : [{BT:"G"} ]}},{Guide:{ Value : "Duplex", Condition : [{BT:"G"} ]}},{Spring:{ Value : "Inconel® X750", Condition : [{BT:"G"} ]}},
        {Base:{ Value : "Duplex", Condition : [{BT:"H"} ]}},{Disc:{ Value : "Duplex", Condition : [{BT:"H"} ]}},{Guide:{ Value : "Duplex", Condition : [{BT:"H"} ]}},{Spring:{ Value : "MP-35N", Condition : [{BT:"H"} ]}},
        {Spindle:{ Value : "416 SST", Condition : [{BT:"0"},{NC:"N"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"1"},{NC:"N"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"2"},{NC:"N"} ]}},
        {Spindle:{ Value : "416 SST", Condition : [{BT:"3"},{NC:"N"} ]}},
        {Spindle:{ Value : "Monel®", Condition : [{BT:"4"},{NC:"N"} ]}},
        {Spindle:{ Value : "416 SST", Condition : [{BT:"5"},{NC:"N"} ]}},
        {Spindle:{ Value : "Hastelloy® C", Condition : [{BT:"6"},{NC:"N"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"7"},{NC:"N"} ]}},
        {Spindle:{ Value : "416 SST", Condition : [{BT:"A"},{NC:"N"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"B"},{NC:"N"} ]}},
        {Spindle:{ Value : "416 SST", Condition : [{BT:"C"},{NC:"N"} ]}},
        {Spindle:{ Value : "Monel®", Condition : [{BT:"D"},{NC:"N"} ]}},
        {Spindle:{ Value : "416 SST", Condition : [{BT:"E"},{NC:"N"} ]}},
        {Spindle:{ Value : "Hastelloy® C", Condition : [{BT:"F"},{NC:"N"} ]}},
        {Spindle:{ Value : "Duplex", Condition : [{BT:"G"},{NC:"N"} ]}},
        {Spindle:{ Value : "Duplex", Condition : [{BT:"H"},{NC:"N"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"0"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"1"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"2"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"3"},{NC:"Y"} ]}},
        {Spindle:{ Value : "Monel®", Condition : [{BT:"4"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"5"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"6"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"7"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"A"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"B"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"C"},{NC:"Y"} ]}},
        {Spindle:{ Value : "Monel®", Condition : [{BT:"D"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"E"},{NC:"Y"} ]}},
        {Spindle:{ Value : "Hastelloy® C", Condition : [{BT:"F"},{NC:"Y"} ]}},
        {Spindle:{ Value : "Duplex", Condition : [{BT:"G"},{NC:"Y"} ]}},
        {Spindle:{ Value : "Duplex", Condition : [{BT:"H"},{NC:"Y"} ]}},
        {Seat:{ Value : "Metal", Condition : [{SM:"1"} ]}},{Seals:{ Value : "N/A", Condition : [{SM:"1"} ]}},
        {Seat:{ Value : "Buna-N (50)", Condition : [{SM:"2"} ]}},{Seals:{ Value : "Buna-N", Condition : [{SM:"2"} ]}},
        {Seat:{ Value : "Buna-N (70)", Condition : [{SM:"3"} ]}},{Seals:{ Value : "Buna-N", Condition : [{SM:"3"} ]}},
        {Seat:{ Value : "Viton® (60)", Condition : [{SM:"4"} ]}},{Seals:{ Value : "Viton®", Condition : [{SM:"4"} ]}},
        {Seat:{ Value : "Viton® (75)", Condition : [{SM:"5"} ]}},{Seals:{ Value : "Viton®", Condition : [{SM:"5"} ]}},
        {Seat:{ Value : "EPR (60)", Condition : [{SM:"6"} ]}},{Seals:{ Value : "EPR", Condition : [{SM:"6"} ]}},
        {Seat:{ Value : "EPR (70)", Condition : [{SM:"7"} ]}},{Seals:{ Value : "EPR", Condition : [{SM:"7"} ]}},
        {Seat:{ Value : "Kalrez® (70)", Condition : [{SM:"8"} ]}},{Seals:{ Value : "Kalrez®", Condition : [{SM:"8"} ]}},
        {Seat:{ Value : "Kalrez® (80)", Condition : [{SM:"9"} ]}},{Seals:{ Value : "Kalrez®", Condition : [{SM:"9"} ]}},
        {Seat:{ Value : "Silicone (50)", Condition : [{SM:"A"} ]}},{Seals:{ Value : "Silicone", Condition : [{SM:"A"} ]}},
        {Seat:{ Value : "Silicone (70)", Condition : [{SM:"B"} ]}},{Seals:{ Value : "Silicone", Condition : [{SM:"B"} ]}},
        {Seat:{ Value : "Teflon®", Condition : [{SM:"0"} ]}},{Seals:{ Value : "Viton®", Condition : [{SM:"0"} ]}},
        {Connections:{ Value : "N/A", Condition : [{CM:"1"} ]}},
        {Connections:{ Value : "Carbon Steel", Condition : [{CM:"2"} ]}},
        {Connections:{ Value : "316 SST", Condition : [{CM:"3"} ]}},
        {Connections:{ Value : "Carbon Steel", Condition : [{CM:"4"} ]}},
        {Connections:{ Value : "316 SST", Condition : [{CM:"5"} ]}},
        {Connections:{ Value : "Carbon Steel", Condition : [{CM:"6"} ]}},
        {Connections:{ Value : "316 SST", Condition : [{CM:"7"} ]}},
        {Connections:{ Value : "Carbon Steel", Condition : [{CM:"8"} ]}},
        {Connections:{ Value : "316 SST", Condition : [{CM:"9"} ]}},
        {Connections:{ Value : "Carbon Steel", Condition : [{CM:"A"} ]}},
        {Connections:{ Value : "316 SST", Condition : [{CM:"B"} ]}},
        {Connections:{ Value : "N/A", Condition : [{CM:"C"} ]}},
        {Connections:{ Value : "N/A", Condition : [{CM:"D"} ]}},
        {Connections:{ Value : "Duplex", Condition : [{CM:"E"} ]}},
        {Connections:{ Value : "Duplex", Condition : [{CM:"F"} ]}},
        {Connections:{ Value : "Duplex", Condition : [{CM:"G"} ]}},
        {CapType:{ Value : "Screwed", Condition : [{CT:"A"} ]}},
        {CapType:{ Value : "Screwed & Test Rod", Condition : [{CT:"B"} ]}},
        {CapType:{ Value : "Packed Lift Lever", Condition : [{CT:"D"} ]}},
        {CapType:{ Value : "Packed Lift Lever & Test Rod", Condition : [{CT:"E"} ]}},
        {Cylinder:{ Value : "CS SA216-WCB", Condition : [{BD:"1"} ]}},
        {Cylinder:{ Value : "SS SA351-CF8M", Condition : [{BD:"2"} ]}},
        {Cylinder:{ Value : "Monel® A494-M35-1", Condition : [{BD:"3"} ]}},
        {Cylinder:{ Value : "Hast.® C SA494-CW-12MW", Condition : [{BD:"4"} ]}},
        {Cylinder:{ Value : "Duplex", Condition : [{BD:"5"} ]}},
        {NACE:{ Value : "No", Condition : [{NC:"N"} ]}},
        {NACE:{ Value : "Yes", Condition : [{NC:"Y"} ]}},
        
        {Accessory1:{ Value : "ASME Code Case 2203", Condition : [{CC:"2"} ]}},
        {InletFinish:{ Value : "RF", Condition : [{FF:"1"} ]}},{OutletFinish:{ Value : "RF", Condition : [{FF:"1"} ]}},
        {InletFinish:{ Value : "RTJ", Condition : [{FF:"2"} ]}},{OutletFinish:{ Value : "RF", Condition : [{FF:"2"} ]}},
        {InletFinish:{ Value : "RTJ", Condition : [{FF:"3"} ]}},{OutletFinish:{ Value : "RTJ", Condition : [{FF:"3"} ]}},
        
        {Accessory1:{ Value : "Rosemount 708 Trans.", Condition : [{VMD:"G"} ]}},
        {Accessory1:{ Value : "Wired Limit Switch", Condition : [{VMD:"C"} ]}},
        {Accessory1:{ Value : "Wireless Limit Switch", Condition : [{VMD:"D"} ]}}
        ]},
        {ModelId:"900", Data:[
        {ValveType:{ Value : "Conventional| Direct Spring-Op", Condition : [{MD:"951"} ]}},{SafetyRelief:{ Value : "Safety Relief", Condition : [{MD:"951"} ]}},{Balanced:{ Value : "No", Condition : [{MD:"951"} ]}},{Nozzle:{ Value : "Full", Condition : [{MD:"951"} ]}},{Bonnet:{ Value : "Closed", Condition : [{MD:"951"} ]}},
        {ValveType:{ Value : "Conventional| Direct Spring-Op", Condition : [{MD:"955"} ]}},{SafetyRelief:{ Value : "Safety Relief", Condition : [{MD:"955"} ]}},{Balanced:{ Value : "No", Condition : [{MD:"955"} ]}},{Nozzle:{ Value : "Full", Condition : [{MD:"955"} ]}},{Bonnet:{ Value : "Closed", Condition : [{MD:"955"} ]}},
        {ValveType:{ Value : "Conventional| Direct Spring-Op", Condition : [{MD:"961"} ]}},{SafetyRelief:{ Value : "Safety Relief", Condition : [{MD:"961"} ]}},{Balanced:{ Value : "No", Condition : [{MD:"961"} ]}},{Nozzle:{ Value : "Full", Condition : [{MD:"961"} ]}},{Bonnet:{ Value : "Closed", Condition : [{MD:"961"} ]}},
        {ValveType:{ Value : "Conventional| Direct Spring-Op", Condition : [{MD:"965"} ]}},{SafetyRelief:{ Value : "Safety Relief", Condition : [{MD:"965"} ]}},{Balanced:{ Value : "No", Condition : [{MD:"965"} ]}},{Nozzle:{ Value : "Full", Condition : [{MD:"965"} ]}},{Bonnet:{ Value : "Closed", Condition : [{MD:"965"} ]}},
        {ValveType:{ Value : "Conventional| Direct Spring-Op", Condition : [{MD:"972"} ]}},{SafetyRelief:{ Value : "Safety Relief", Condition : [{MD:"972"} ]}},{Balanced:{ Value : "No", Condition : [{MD:"972"} ]}},{Nozzle:{ Value : "Full", Condition : [{MD:"972"} ]}},{Bonnet:{ Value : "Closed", Condition : [{MD:"972"} ]}},
        {ValveType:{ Value : "Conventional| Direct Spring-Op", Condition : [{MD:"981"} ]}},{SafetyRelief:{ Value : "Safety Relief", Condition : [{MD:"981"} ]}},{Balanced:{ Value : "No", Condition : [{MD:"981"} ]}},{Nozzle:{ Value : "Full", Condition : [{MD:"981"} ]}},{Bonnet:{ Value : "Closed", Condition : [{MD:"981"} ]}},
        {ValveType:{ Value : "Conventional| Direct Spring-Op", Condition : [{MD:"991"} ]}},{SafetyRelief:{ Value : "Safety Relief", Condition : [{MD:"991"} ]}},{Balanced:{ Value : "No", Condition : [{MD:"991"} ]}},{Nozzle:{ Value : "Full", Condition : [{MD:"991"} ]}},{Bonnet:{ Value : "Closed", Condition : [{MD:"991"} ]}},
        {InletSize:{ Value : "1/2", Condition : [{CS:"0"} ]}},{OutletSize:{ Value : "1", Condition : [{CS:"0"} ]}},
        {InletSize:{ Value : "3/4", Condition : [{CS:"1"} ]}},{OutletSize:{ Value : "1", Condition : [{CS:"1"} ]}},
        {InletSize:{ Value : "1", Condition : [{CS:"2"} ]}},{OutletSize:{ Value : "1", Condition : [{CS:"2"} ]}},
        {InletSize:{ Value : "1", Condition : [{CS:"3"} ]}},{OutletSize:{ Value : "1 1/2", Condition : [{CS:"3"} ]}},
        {InletSize:{ Value : "1 1/2", Condition : [{CS:"4"} ]}},{OutletSize:{ Value : "1 1/2", Condition : [{CS:"4"} ]}},
        {InletSize:{ Value : "1 1/2", Condition : [{CS:"5"} ]}},{OutletSize:{ Value : "2", Condition : [{CS:"5"} ]}},
        {InletSize:{ Value : "2", Condition : [{CS:"6"} ]}},{OutletSize:{ Value : "2", Condition : [{CS:"6"} ]}},
        {InletSize:{ Value : "1 1/2", Condition : [{CS:"7"} ]}},{OutletSize:{ Value : "2 1/2", Condition : [{CS:"7"} ]}},
        {InletConn:{ Value : "Thrd.", Condition : [{VC:"M"} ]}},{InletFinish:{ Value : "MNPT", Condition : [{VC:"M"} ]}},{OutletConn:{ Value : "Thrd.", Condition : [{VC:"M"} ]}},{OutletFinish:{ Value : "FNPT", Condition : [{VC:"M"} ]}},{Standard:{ Value : "ASME B1.20.1", Condition : [{VC:"M"} ]}},
        {InletConn:{ Value : "Thrd.", Condition : [{VC:"F"} ]}},{InletFinish:{ Value : "FNPT", Condition : [{VC:"F"} ]}},{OutletConn:{ Value : "Thrd.", Condition : [{VC:"F"} ]}},{OutletFinish:{ Value : "FNPT", Condition : [{VC:"F"} ]}},{Standard:{ Value : "ASME B1.20.1", Condition : [{VC:"F"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{VC:"1"} ]}},{InletRating:{ Value : "150#", Condition : [{VC:"1"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{VC:"1"} ]}},{OutletRating:{ Value : "150#", Condition : [{VC:"1"} ]}},{Standard:{ Value : "ASME B16.5", Condition : [{VC:"1"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{VC:"2"} ]}},{InletRating:{ Value : "300#", Condition : [{VC:"2"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{VC:"2"} ]}},{OutletRating:{ Value : "150#", Condition : [{VC:"2"} ]}},{Standard:{ Value : "ASME B16.5", Condition : [{VC:"2"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{VC:"A"} ]}},{InletRating:{ Value : "300#", Condition : [{VC:"A"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{VC:"A"} ]}},{OutletRating:{ Value : "300#", Condition : [{VC:"A"} ]}},{Standard:{ Value : "ASME B16.5", Condition : [{VC:"A"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{VC:"3"} ]}},{InletRating:{ Value : "600#", Condition : [{VC:"3"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{VC:"3"} ]}},{OutletRating:{ Value : "150#", Condition : [{VC:"3"} ]}},{Standard:{ Value : "ASME B16.5", Condition : [{VC:"3"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{VC:"B"} ]}},{InletRating:{ Value : "600#", Condition : [{VC:"B"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{VC:"B"} ]}},{OutletRating:{ Value : "300#", Condition : [{VC:"B"} ]}},{Standard:{ Value : "ASME B16.5", Condition : [{VC:"B"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{VC:"4"} ]}},{InletRating:{ Value : "1500#", Condition : [{VC:"4"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{VC:"4"} ]}},{OutletRating:{ Value : "300#", Condition : [{VC:"4"} ]}},{Standard:{ Value : "ASME B16.5", Condition : [{VC:"4"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{VC:"5"} ]}},{InletRating:{ Value : "2500#", Condition : [{VC:"5"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{VC:"5"} ]}},{OutletRating:{ Value : "300#", Condition : [{VC:"5"} ]}},{Standard:{ Value : "ASME B16.5", Condition : [{VC:"5"} ]}},
        {InletConn:{ Value : "Welded", Condition : [{VC:"8"} ]}},{InletFinish:{ Value : "Male SW", Condition : [{VC:"8"} ]}},{OutletConn:{ Value : "Welded", Condition : [{VC:"8"} ]}},{OutletFinish:{ Value : "Male SW", Condition : [{VC:"8"} ]}},
        {InletConn:{ Value : "Thrd.", Condition : [{VC:"9"} ]}},{InletFinish:{ Value : "MNPT", Condition : [{VC:"9"} ]}},{OutletConn:{ Value : "Thrd.", Condition : [{VC:"9"} ]}},{OutletFinish:{ Value : "FNPT", Condition : [{VC:"9"} ]}},{Standard:{ Value : "ASME B1.20.1", Condition : [{VC:"9"} ]}},
        {Base:{ Value : "316 SST", Condition : [{BT:"0"} ]}},{Disc:{ Value : "316 SST", Condition : [{BT:"0"} ]}},{Guide:{ Value : "316 SST", Condition : [{BT:"0"} ]}},{Spring:{ Value : "17-7 PH SST", Condition : [{BT:"0"} ]}},
        {Base:{ Value : "316 SST", Condition : [{BT:"1"} ]}},{Disc:{ Value : "316 SST", Condition : [{BT:"1"} ]}},{Guide:{ Value : "316 SST", Condition : [{BT:"1"} ]}},{Spring:{ Value : "316 SST", Condition : [{BT:"1"} ]}},
        {Base:{ Value : "316 SST", Condition : [{BT:"2"} ]}},{Disc:{ Value : "316 SST", Condition : [{BT:"2"} ]}},{Guide:{ Value : "316 SST", Condition : [{BT:"2"} ]}},{Spring:{ Value : "Inconel® X750", Condition : [{BT:"2"} ]}},
        {Base:{ Value : "Monel®", Condition : [{BT:"3"} ]}},{Disc:{ Value : "Monel®", Condition : [{BT:"3"} ]}},{Guide:{ Value : "Monel®", Condition : [{BT:"3"} ]}},{Spring:{ Value : "Inconel® X750", Condition : [{BT:"3"} ]}},
        {Base:{ Value : "Monel®", Condition : [{BT:"4"} ]}},{Disc:{ Value : "Monel®", Condition : [{BT:"4"} ]}},{Guide:{ Value : "Monel®", Condition : [{BT:"4"} ]}},{Spring:{ Value : "Inconel® X750", Condition : [{BT:"4"} ]}},
        {Base:{ Value : "Hastelloy® C", Condition : [{BT:"5"} ]}},{Disc:{ Value : "Hastelloy® C", Condition : [{BT:"5"} ]}},{Guide:{ Value : "Hastelloy® C", Condition : [{BT:"5"} ]}},{Spring:{ Value : "Inconel® X750", Condition : [{BT:"5"} ]}},
        {Base:{ Value : "Hastelloy® C", Condition : [{BT:"6"} ]}},{Disc:{ Value : "Hastelloy® C", Condition : [{BT:"6"} ]}},{Guide:{ Value : "Hastelloy® C", Condition : [{BT:"6"} ]}},{Spring:{ Value : "Hastelloy® C", Condition : [{BT:"6"} ]}},
        {Base:{ Value : "316 SST", Condition : [{BT:"7"} ]}},{Disc:{ Value : "316 SST", Condition : [{BT:"7"} ]}},{Guide:{ Value : "316 SST", Condition : [{BT:"7"} ]}},{Spring:{ Value : "Inconel® X750", Condition : [{BT:"7"} ]}},
        {Base:{ Value : "316 SST", Condition : [{BT:"A"} ]}},{Disc:{ Value : "316 SST", Condition : [{BT:"A"} ]}},{Guide:{ Value : "316 SST", Condition : [{BT:"A"} ]}},{Spring:{ Value : "MP-35N", Condition : [{BT:"A"} ]}},
        {Base:{ Value : "316 SST", Condition : [{BT:"B"} ]}},{Disc:{ Value : "316 SST", Condition : [{BT:"B"} ]}},{Guide:{ Value : "316 SST", Condition : [{BT:"B"} ]}},{Spring:{ Value : "MP-35N", Condition : [{BT:"B"} ]}},
        {Base:{ Value : "Monel®", Condition : [{BT:"C"} ]}},{Disc:{ Value : "Monel®", Condition : [{BT:"C"} ]}},{Guide:{ Value : "Monel®", Condition : [{BT:"C"} ]}},{Spring:{ Value : "MP-35N", Condition : [{BT:"C"} ]}},
        {Base:{ Value : "Monel®", Condition : [{BT:"D"} ]}},{Disc:{ Value : "Monel®", Condition : [{BT:"D"} ]}},{Guide:{ Value : "Monel®", Condition : [{BT:"D"} ]}},{Spring:{ Value : "MP-35N", Condition : [{BT:"D"} ]}},
        {Base:{ Value : "Hastelloy® C", Condition : [{BT:"E"} ]}},{Disc:{ Value : "Hastelloy® C", Condition : [{BT:"E"} ]}},{Guide:{ Value : "Hastelloy® C", Condition : [{BT:"E"} ]}},{Spring:{ Value : "MP-35N", Condition : [{BT:"E"} ]}},
        {Base:{ Value : "Hastelloy® C", Condition : [{BT:"F"} ]}},{Disc:{ Value : "Hastelloy® C", Condition : [{BT:"F"} ]}},{Guide:{ Value : "Hastelloy® C", Condition : [{BT:"F"} ]}},{Spring:{ Value : "MP-35N", Condition : [{BT:"F"} ]}},
        {Base:{ Value : "Duplex", Condition : [{BT:"G"} ]}},{Disc:{ Value : "Duplex", Condition : [{BT:"G"} ]}},{Guide:{ Value : "Duplex", Condition : [{BT:"G"} ]}},{Spring:{ Value : "Inconel® X750", Condition : [{BT:"G"} ]}},
        {Base:{ Value : "Duplex", Condition : [{BT:"H"} ]}},{Disc:{ Value : "Duplex", Condition : [{BT:"H"} ]}},{Guide:{ Value : "Duplex", Condition : [{BT:"H"} ]}},{Spring:{ Value : "MP-35N", Condition : [{BT:"H"} ]}},
        {Spindle:{ Value : "416 SST", Condition : [{BT:"0"},{NC:"N"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"1"},{NC:"N"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"2"},{NC:"N"} ]}},
        {Spindle:{ Value : "416 SST", Condition : [{BT:"3"},{NC:"N"} ]}},
        {Spindle:{ Value : "Monel®", Condition : [{BT:"4"},{NC:"N"} ]}},
        {Spindle:{ Value : "416 SST", Condition : [{BT:"5"},{NC:"N"} ]}},
        {Spindle:{ Value : "Hastelloy® C", Condition : [{BT:"6"},{NC:"N"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"7"},{NC:"N"} ]}},
        {Spindle:{ Value : "416 SST", Condition : [{BT:"A"},{NC:"N"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"B"},{NC:"N"} ]}},
        {Spindle:{ Value : "416 SST", Condition : [{BT:"C"},{NC:"N"} ]}},
        {Spindle:{ Value : "Monel®", Condition : [{BT:"D"},{NC:"N"} ]}},
        {Spindle:{ Value : "416 SST", Condition : [{BT:"E"},{NC:"N"} ]}},
        {Spindle:{ Value : "Hastelloy® C", Condition : [{BT:"F"},{NC:"N"} ]}},
        {Spindle:{ Value : "Duplex", Condition : [{BT:"G"},{NC:"N"} ]}},
        {Spindle:{ Value : "Duplex", Condition : [{BT:"H"},{NC:"N"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"0"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"1"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"2"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"3"},{NC:"Y"} ]}},
        {Spindle:{ Value : "Monel®", Condition : [{BT:"4"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"5"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"6"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"7"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"A"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"B"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"C"},{NC:"Y"} ]}},
        {Spindle:{ Value : "Monel®", Condition : [{BT:"D"},{NC:"Y"} ]}},
        {Spindle:{ Value : "316 SST", Condition : [{BT:"E"},{NC:"Y"} ]}},
        {Spindle:{ Value : "Hastelloy® C", Condition : [{BT:"F"},{NC:"Y"} ]}},
        {Spindle:{ Value : "Duplex", Condition : [{BT:"G"},{NC:"Y"} ]}},
        {Spindle:{ Value : "Duplex", Condition : [{BT:"H"},{NC:"Y"} ]}},
        {Seat:{ Value : "Metal", Condition : [{SM:"1"} ]}},{Seals:{ Value : "N/A", Condition : [{SM:"1"} ]}},
        {Seat:{ Value : "Buna-N (50)", Condition : [{SM:"2"} ]}},{Seals:{ Value : "N/A", Condition : [{SM:"2"} ]}},
        {Seat:{ Value : "Buna-N (70)", Condition : [{SM:"3"} ]}},{Seals:{ Value : "N/A", Condition : [{SM:"3"} ]}},
        {Seat:{ Value : "Viton® (60)", Condition : [{SM:"4"} ]}},{Seals:{ Value : "N/A", Condition : [{SM:"4"} ]}},
        {Seat:{ Value : "Viton® (75)", Condition : [{SM:"5"} ]}},{Seals:{ Value : "N/A", Condition : [{SM:"5"} ]}},
        {Seat:{ Value : "EPR (60)", Condition : [{SM:"6"} ]}},{Seals:{ Value : "N/A", Condition : [{SM:"6"} ]}},
        {Seat:{ Value : "EPR (70)", Condition : [{SM:"7"} ]}},{Seals:{ Value : "N/A", Condition : [{SM:"7"} ]}},
        {Seat:{ Value : "Kalrez® (70)", Condition : [{SM:"8"} ]}},{Seals:{ Value : "N/A", Condition : [{SM:"8"} ]}},
        {Seat:{ Value : "Kalrez® (80)", Condition : [{SM:"9"} ]}},{Seals:{ Value : "N/A", Condition : [{SM:"9"} ]}},
        {Seat:{ Value : "Teflon®", Condition : [{SM:"0"} ]}},{Seals:{ Value : "N/A", Condition : [{SM:"0"} ]}},
        {Seat:{ Value : "Silicone (50)", Condition : [{SM:"A"} ]}},{Seals:{ Value : "N/A", Condition : [{SM:"A"} ]}},
        {Seat:{ Value : "Silicone (70)", Condition : [{SM:"B"} ]}},{Seals:{ Value : "N/A", Condition : [{SM:"B"} ]}},
        {Connections:{ Value : "N/A", Condition : [{CM:"1"} ]}},
        {Connections:{ Value : "Carbon Steel", Condition : [{CM:"2"} ]}},
        {Connections:{ Value : "316 SST", Condition : [{CM:"3"} ]}},
        {Connections:{ Value : "Carbon Steel", Condition : [{CM:"4"} ]}},
        {Connections:{ Value : "316 SST", Condition : [{CM:"5"} ]}},
        {Connections:{ Value : "Carbon Steel", Condition : [{CM:"6"} ]}},
        {Connections:{ Value : "316 SST", Condition : [{CM:"7"} ]}},
        {Connections:{ Value : "Carbon Steel", Condition : [{CM:"8"} ]}},
        {Connections:{ Value : "316 SST", Condition : [{CM:"9"} ]}},
        {Connections:{ Value : "Carbon Steel", Condition : [{CM:"A"} ]}},
        {Connections:{ Value : "316 SST", Condition : [{CM:"B"} ]}},
        {Connections:{ Value : "N/A", Condition : [{CM:"C"} ]}},
        {Connections:{ Value : "N/A", Condition : [{CM:"D"} ]}},
        {Connections:{ Value : "Duplex", Condition : [{CM:"E"} ]}},
        {Connections:{ Value : "Duplex", Condition : [{CM:"F"} ]}},
        {Connections:{ Value : "Duplex", Condition : [{CM:"G"} ]}},
        {CapType:{ Value : "Screwed", Condition : [{CT:"A"} ]}},
        {CapType:{ Value : "Screwed & Test Rod", Condition : [{CT:"B"} ]}},
        {CapType:{ Value : "Packed Lift Lever", Condition : [{CT:"D"} ]}},
        {CapType:{ Value : "Packed Lift Lever & Test Rod", Condition : [{CT:"E"} ]}},
        {Cylinder:{ Value : "CS SA216-WCB", Condition : [{BD:"1"} ]}},
        {Cylinder:{ Value : "SS SA351-CF8M", Condition : [{BD:"2"} ]}},
        {Cylinder:{ Value : "Monel® A494-M35-1", Condition : [{BD:"3"} ]}},
        {Cylinder:{ Value : "Hast.® C SA494-CW-12MW", Condition : [{BD:"4"} ]}},
        {Cylinder:{ Value : "Duplex", Condition : [{BD:"5"} ]}},
        {NACE:{ Value : "No", Condition : [{NC:"N"} ]}},
        {NACE:{ Value : "Yes", Condition : [{NC:"Y"} ]}},
        
        {Accessory1:{ Value : "ASME Code Case 2203", Condition : [{CC:"2"} ]}},
        {InletFinish:{ Value : "RF", Condition : [{FF:"1"} ]}},{OutletFinish:{ Value : "RF", Condition : [{FF:"1"} ]}},
        {InletFinish:{ Value : "RTJ", Condition : [{FF:"2"} ]}},{OutletFinish:{ Value : "RF", Condition : [{FF:"2"} ]}},
        {InletFinish:{ Value : "RTJ", Condition : [{FF:"3"} ]}},{OutletFinish:{ Value : "RTJ", Condition : [{FF:"3"} ]}},
        {Accessory1:{ Value : "Special Bolted Cylinder", Condition : [{PT:"R"} ]}},
        
        {Accessory1:{ Value : "Rosemount 708 Trans.", Condition : [{VMD:"G"} ]}},
        {Accessory1:{ Value : "Wired Limit Switch", Condition : [{VMD:"C"} ]}},
        {Accessory1:{ Value : "Wireless Limit Switch", Condition : [{VMD:"D"} ]}}
        
        ]}
]

module.exports = {
    highPres_CBP_CCS
};