const lowPres_APOAPO = [
    {ModelId:"9299C SC", Data:[
        {ValveType:{ Value : "Pilot-Operated Pressure & Vacuum", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"A"},{APP:"C"} ]}},{SafetyRelief:{ Value : "Safety", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"A"},{APP:"C"} ]}},{Balanced:{ Value : "Yes", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"A"},{APP:"C"} ]}},{Nozzle:{ Value : "Full", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"A"},{APP:"C"} ]}},{Bonnet:{ Value : "Vented", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"A"},{APP:"C"} ]}},{Standard:{ Value : "ASME B16.5", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"A"},{APP:"C"} ]}},{Tubing:{ Value : "316 SST", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"A"},{APP:"C"} ]}},{Fittings:{ Value : "316 SST CPI", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"A"},{APP:"C"} ]}},
        {ValveType:{ Value : "Pilot-Operated Pressure & Vacuum", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"A"},{APP:"C"} ]}},{SafetyRelief:{ Value : "Safety", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"A"},{APP:"C"} ]}},{Balanced:{ Value : "Yes", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"A"},{APP:"C"} ]}},{Nozzle:{ Value : "Full", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"A"},{APP:"C"} ]}},{Bonnet:{ Value : "Vented", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"A"},{APP:"C"} ]}},{Tubing:{ Value : "316 SST", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"A"},{APP:"C"} ]}},{Fittings:{ Value : "316 SST CPI", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"A"},{APP:"C"} ]}},
        {ValveType:{ Value : "Pilot-Operated Pressure & Vacuum", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"B"},{APP:"C"} ]}},{SafetyRelief:{ Value : "Safety", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"B"},{APP:"C"} ]}},{Balanced:{ Value : "Yes", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"B"},{APP:"C"} ]}},{Nozzle:{ Value : "Full", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"B"},{APP:"C"} ]}},{Bonnet:{ Value : "Vented", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"B"},{APP:"C"} ]}},{Tubing:{ Value : "316 SST", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"B"},{APP:"C"} ]}},{Fittings:{ Value : "316 SST CPI", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"B"},{APP:"C"} ]}},
        {ValveType:{ Value : "Pilot-Operated Pressure & Vacuum", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"B"},{APP:"C"} ]}},{SafetyRelief:{ Value : "Safety", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"B"},{APP:"C"} ]}},{Balanced:{ Value : "Yes", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"B"},{APP:"C"} ]}},{Nozzle:{ Value : "Full", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"B"},{APP:"C"} ]}},{Bonnet:{ Value : "Vented", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"B"},{APP:"C"} ]}},{Tubing:{ Value : "316 SST", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"B"},{APP:"C"} ]}},{Fittings:{ Value : "316 SST CPI", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"B"},{APP:"C"} ]}},
        {InletSize:{ Value : '2"', Condition : [{IS:"2"} ]}},{InletRating:{ Value : "150#", Condition : [{IS:"2"} ]}},
        {InletSize:{ Value : '3"', Condition : [{IS:"3"} ]}},{InletRating:{ Value : "150#", Condition : [{IS:"3"} ]}},
        {InletSize:{ Value : '4"', Condition : [{IS:"4"} ]}},{InletRating:{ Value : "150#", Condition : [{IS:"4"} ]}},
        {InletSize:{ Value : '6"', Condition : [{IS:"6"} ]}},{InletRating:{ Value : "150#", Condition : [{IS:"6"} ]}},
        {InletSize:{ Value : '8"', Condition : [{IS:"8"} ]}},{InletRating:{ Value : "150#", Condition : [{IS:"8"} ]}},
        {InletSize:{ Value : '10"', Condition : [{IS:"0"} ]}},{InletRating:{ Value : "150#", Condition : [{IS:"0"} ]}},
        {InletSize:{ Value : '12"', Condition : [{IS:"1"} ]}},{InletRating:{ Value : "150#", Condition : [{IS:"1"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{FF:"1"} ]}},{InletFinish:{ Value : "RF", Condition : [{FF:"1"} ]}},
        {BodyBase:{ Value : "AL B209-6061-T6 (Base)", Condition : [{BM:"A"} ]}},{Nozzle:{ Value : "316 SST", Condition : [{BM:"A"} ]}},
        {BodyBase:{ Value : "SS A351-CF8M (Base)", Condition : [{BM:"S"} ]}},{Nozzle:{ Value : "316 SST", Condition : [{BM:"S"} ]}},
        {CapCase:{ Value : "SS A240-304/316 (Single)", Condition : [{DC:"S"} ]}},
        {Trim:{ Value : "AL", Condition : [{BTM:"A"} ]}},
        {Trim:{ Value : "SST (LP)", Condition : [{BTM:"S"} ]}},
        {Seat:{ Value : "FEP (Film)", Condition : [{BSG:"T"} ]}},{SoftGoods:{ Value : "Teflon®", Condition : [{BSG:"T"} ]}},
        {PressurePilotBody:{ Value : "AL 6061-T651", Condition : [{PBM:"A"} ]}},
        {PressurePilotBody:{ Value : "SS A479-316/316L", Condition : [{PBM:"S"} ]}},
        {Seat:{ Value : "Teflon®", Condition : [{PSG:"1"} ]}},{SoftGoods:{ Value : "Teflon®", Condition : [{PSG:"1"} ]}},
        {Seat:{ Value : "Buna-N", Condition : [{PSG:"2"} ]}},{SoftGoods:{ Value : "Buna-N", Condition : [{PSG:"2"} ]}},
        {Seat:{ Value : "Viton®", Condition : [{PSG:"3"} ]}},{SoftGoods:{ Value : "Viton®", Condition : [{PSG:"3"} ]}},
        {Seat:{ Value : "EPR", Condition : [{PSG:"4"} ]}},{SoftGoods:{ Value : "EPR", Condition : [{PSG:"4"} ]}},
        {Seat:{ Value : "Buna-N", Condition : [{PSG:"5"} ]}},{SoftGoods:{ Value : "Buna-N", Condition : [{PSG:"5"} ]}},
        {Seat:{ Value : "Viton®", Condition : [{PSG:"6"} ]}},{SoftGoods:{ Value : "Viton®", Condition : [{PSG:"6"} ]}},
        {Seat:{ Value : "EPR", Condition : [{PSG:"7"} ]}},{SoftGoods:{ Value : "EPR", Condition : [{PSG:"7"} ]}},
        {Seat:{ Value : "Kalrez®", Condition : [{PSG:"8"} ]}},{SoftGoods:{ Value : "Kalrez®", Condition : [{PSG:"8"} ]}},
        {Diaphragm:{ Value : "Buna-N", Condition : [{PD:"B"} ]}},
        {Diaphragm:{ Value : "Viton®", Condition : [{PD:"V"} ]}},
        {Diaphragm:{ Value : "EPR", Condition : [{PD:"E"} ]}},
        {Diaphragm:{ Value : "Teflon®", Condition : [{PD:"T"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"A"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"B"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"C"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"D"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"E"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"F"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"G"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"H"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"J"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"K"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"2"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"3"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"4"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"5"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"6"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"7"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"8"} ]}},
        {Body:{ Value : "AL 6061-T651", Condition : [{PBM:"A"} ]}},
        {Body:{ Value : "SS A479-316/316L", Condition : [{PBM:"S"} ]}},
        {Seat:{ Value : "Teflon®", Condition : [{PSG:"1"} ]}},{SoftGoods:{ Value : "Teflon®", Condition : [{PSG:"1"} ]}},
        {Seat:{ Value : "Buna-N", Condition : [{PSG:"2"} ]}},{SoftGoods:{ Value : "Buna-N", Condition : [{PSG:"2"} ]}},
        {Seat:{ Value : "Viton®", Condition : [{PSG:"3"} ]}},{SoftGoods:{ Value : "Viton®", Condition : [{PSG:"3"} ]}},
        {Seat:{ Value : "EPR", Condition : [{PSG:"4"} ]}},{SoftGoods:{ Value : "EPR", Condition : [{PSG:"4"} ]}},
        {Seat:{ Value : "Buna-N", Condition : [{PSG:"5"} ]}},{SoftGoods:{ Value : "Buna-N", Condition : [{PSG:"5"} ]}},
        {Seat:{ Value : "Viton®", Condition : [{PSG:"6"} ]}},{SoftGoods:{ Value : "Viton®", Condition : [{PSG:"6"} ]}},
        {Seat:{ Value : "EPR", Condition : [{PSG:"7"} ]}},{SoftGoods:{ Value : "EPR", Condition : [{PSG:"7"} ]}},
        {Seat:{ Value : "Kalrez", Condition : [{PSG:"8"} ]}},{SoftGoods:{ Value : "Kalrez", Condition : [{PSG:"8"} ]}},
        {Diaphragm:{ Value : "Buna-N", Condition : [{PD:"B"} ]}},
        {Diaphragm:{ Value : "Viton®", Condition : [{PD:"V"} ]}},
        {Diaphragm:{ Value : "EPR", Condition : [{PD:"E"} ]}},
        {Diaphragm:{ Value : "Teflon®", Condition : [{PD:"T"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{VS:"A"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{VS:"B"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{VS:"C"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{VS:"D"} ]}},
        {Accessory1:{ Value : "Integral Sense", Condition : [{ST:"S"} ]}},
        {Accessory1:{ Value : "Remote Sense Connect.", Condition : [{ST:"E"} ]}},
        
        {Accessory1:{ Value : "Pilot Gag", Condition : [{PA:"A"} ]}},
        {Accessory1:{ Value : "Lift Lever", Condition : [{PA:"B"} ]}},
        {Accessory1:{ Value : "Pilot Gag", Condition : [{PA:"C"} ]}},{Accessory2:{ Value : "Lift Lever", Condition : [{PA:"C"} ]}},
        
        {Accessory1:{ Value : "SS 3-Way Ball Valve", Condition : [{VAL1:"1"} ]}},
        {Accessory1:{ Value : "SS 3Way Bll Vlv w/ Lck Tb", Condition : [{VAL1:"2"} ]}},
        
        {Accessory1:{ Value : "SS Hand Vlv & Check Vlv", Condition : [{VAL2:"1"} ]}},
        {Accessory1:{ Value : "AL Hand Vlv & Check Vlv", Condition : [{VAL2:"2"} ]}},
        
        {Accessory1:{ Value : "SS Manual Unloader", Condition : [{VAL3:"1"} ]}},
        
        {Accessory1:{ Value : "SS Manual Unloader", Condition : [{VAL4:"1"} ]}},
        {Accessory1:{ Value : "Remote Unloader", Condition : [{VAL4:"2"} ]}},
        
        {Accessory1:{ Value : "SS Aux. Filter w/ Drain", Condition : [{VAL5:"1"} ]}},
        {Accessory1:{ Value : "CS Aux. Filter w/ Drain", Condition : [{VAL5:"2"} ]}},
        
        {Accessory1:{ Value : "SS Back Flow Preventer", Condition : [{VAL6:"1"} ]}},
        {Accessory1:{ Value : "AL Back Flow Preventer", Condition : [{VAL6:"2"} ]}}
        ]},
        {ModelId:"9399C SC", Data:[
        {ValveType:{ Value : "Pilot-Operated Pressure & Vacuum", Condition : [{MOD:"93"},{PPT:"A"},{VPT:"A"},{APP:"C"} ]}},{SafetyRelief:{ Value : "Safety", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"A"},{APP:"C"} ]}},{Balanced:{ Value : "Yes", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"A"},{APP:"C"} ]}},{Nozzle:{ Value : "Full", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"A"},{APP:"C"} ]}},{Bonnet:{ Value : "Vented", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"A"},{APP:"C"} ]}},{Standard:{ Value : "ASME B16.5", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"A"},{APP:"C"} ]}},{Tubing:{ Value : "316 SST", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"A"},{APP:"C"} ]}},{Fittings:{ Value : "316 SST CPI", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"A"},{APP:"C"} ]}},
        {ValveType:{ Value : "Pilot-Operated Pressure & Vacuum", Condition : [{MOD:"93"},{PPT:"B"},{VPT:"A"},{APP:"C"} ]}},{SafetyRelief:{ Value : "Safety", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"A"},{APP:"C"} ]}},{Balanced:{ Value : "Yes", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"A"},{APP:"C"} ]}},{Nozzle:{ Value : "Full", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"A"},{APP:"C"} ]}},{Bonnet:{ Value : "Vented", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"A"},{APP:"C"} ]}},{Tubing:{ Value : "316 SST", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"A"},{APP:"C"} ]}},{Fittings:{ Value : "316 SST CPI", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"A"},{APP:"C"} ]}},
        {ValveType:{ Value : "Pilot-Operated Pressure & Vacuum", Condition : [{MOD:"93"},{PPT:"C"},{VPT:"A"},{APP:"C"} ]}},{SafetyRelief:{ Value : "Safety", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"B"},{APP:"C"} ]}},{Balanced:{ Value : "Yes", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"B"},{APP:"C"} ]}},{Nozzle:{ Value : "Full", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"B"},{APP:"C"} ]}},{Bonnet:{ Value : "Vented", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"B"},{APP:"C"} ]}},{Tubing:{ Value : "316 SST", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"B"},{APP:"C"} ]}},{Fittings:{ Value : "316 SST CPI", Condition : [{MOD:"92"},{PPT:"B"},{VPT:"B"},{APP:"C"} ]}},
        {ValveType:{ Value : "Pilot-Operated Pressure & Vacuum", Condition : [{MOD:"93"},{PPT:"D"},{VPT:"A"},{APP:"C"} ]}},{SafetyRelief:{ Value : "Safety", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"B"},{APP:"C"} ]}},{Balanced:{ Value : "Yes", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"B"},{APP:"C"} ]}},{Nozzle:{ Value : "Full", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"B"},{APP:"C"} ]}},{Bonnet:{ Value : "Vented", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"B"},{APP:"C"} ]}},{Tubing:{ Value : "316 SST", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"B"},{APP:"C"} ]}},{Fittings:{ Value : "316 SST CPI", Condition : [{MOD:"92"},{PPT:"C"},{VPT:"B"},{APP:"C"} ]}},
        {ValveType:{ Value : "Pilot-Operated Pressure & Vacuum", Condition : [{MOD:"93"},{PPT:"E"},{VPT:"A"},{APP:"C"} ]}},{SafetyRelief:{ Value : "Safety", Condition : [{IS:"2"} ]}},{Balanced:{ Value : "Yes", Condition : [{IS:"2"} ]}},{Nozzle:{ Value : "Full", Condition : [{IS:"2"} ]}},{Bonnet:{ Value : "Vented", Condition : [{IS:"2"} ]}},{Tubing:{ Value : "316 SST", Condition : [{IS:"2"} ]}},{Fittings:{ Value : "316 SST CPI", Condition : [{IS:"2"} ]}},
        {ValveType:{ Value : "Pilot-Operated Pressure & Vacuum", Condition : [{MOD:"93"},{PPT:"A"},{VPT:"B"},{APP:"C"} ]}},{SafetyRelief:{ Value : "Safety", Condition : [{IS:"3"} ]}},{Balanced:{ Value : "Yes", Condition : [{IS:"3"} ]}},{Nozzle:{ Value : "Full", Condition : [{IS:"3"} ]}},{Bonnet:{ Value : "Vented", Condition : [{IS:"3"} ]}},{Tubing:{ Value : "316 SST", Condition : [{IS:"3"} ]}},{Fittings:{ Value : "316 SST CPI", Condition : [{IS:"3"} ]}},
        {ValveType:{ Value : "Pilot-Operated Pressure & Vacuum", Condition : [{MOD:"93"},{PPT:"B"},{VPT:"B"},{APP:"C"} ]}},{SafetyRelief:{ Value : "Safety", Condition : [{IS:"4"} ]}},{Balanced:{ Value : "Yes", Condition : [{IS:"4"} ]}},{Nozzle:{ Value : "Full", Condition : [{IS:"4"} ]}},{Bonnet:{ Value : "Vented", Condition : [{IS:"4"} ]}},{Tubing:{ Value : "316 SST", Condition : [{IS:"4"} ]}},{Fittings:{ Value : "316 SST CPI", Condition : [{IS:"4"} ]}},
        {ValveType:{ Value : "Pilot-Operated Pressure & Vacuum", Condition : [{MOD:"93"},{PPT:"C"},{VPT:"B"},{APP:"C"} ]}},{SafetyRelief:{ Value : "Safety", Condition : [{IS:"6"} ]}},{Balanced:{ Value : "Yes", Condition : [{IS:"6"} ]}},{Nozzle:{ Value : "Full", Condition : [{IS:"6"} ]}},{Bonnet:{ Value : "Vented", Condition : [{IS:"6"} ]}},{Tubing:{ Value : "316 SST", Condition : [{IS:"6"} ]}},{Fittings:{ Value : "316 SST CPI", Condition : [{IS:"6"} ]}},
        {ValveType:{ Value : "Pilot-Operated Pressure & Vacuum", Condition : [{MOD:"93"},{PPT:"D"},{VPT:"B"},{APP:"C"} ]}},{SafetyRelief:{ Value : "Safety", Condition : [{IS:"8"} ]}},{Balanced:{ Value : "Yes", Condition : [{IS:"8"} ]}},{Nozzle:{ Value : "Full", Condition : [{IS:"8"} ]}},{Bonnet:{ Value : "Vented", Condition : [{IS:"8"} ]}},{Tubing:{ Value : "316 SST", Condition : [{IS:"8"} ]}},{Fittings:{ Value : "316 SST CPI", Condition : [{IS:"8"} ]}},
        {ValveType:{ Value : "Pilot-Operated Pressure & Vacuum", Condition : [{MOD:"93"},{PPT:"E"},{VPT:"B"},{APP:"C"} ]}},{SafetyRelief:{ Value : "Safety", Condition : [{IS:"0"} ]}},{Balanced:{ Value : "Yes", Condition : [{IS:"0"} ]}},{Nozzle:{ Value : "Full", Condition : [{IS:"0"} ]}},{Bonnet:{ Value : "Vented", Condition : [{IS:"0"} ]}},{Tubing:{ Value : "316 SST", Condition : [{IS:"0"} ]}},{Fittings:{ Value : "316 SST CPI", Condition : [{IS:"0"} ]}},
        {InletSize:{ Value : "2", Condition : [{IS:"1"} ]}},{InletRating:{ Value : "150#", Condition : [{IS:"1"} ]}},{OutletSize:{ Value : "3", Condition : [{IS:"1"} ]}},{OutletRating:{ Value : "150#", Condition : [{IS:"1"} ]}},
        {InletSize:{ Value : "3", Condition : [{FF:"1"} ]}},{InletRating:{ Value : "150#", Condition : [{FF:"1"} ]}},{OutletSize:{ Value : "4", Condition : [{FF:"1"} ]}},{OutletRating:{ Value : "150#", Condition : [{FF:"1"} ]}},
        {InletSize:{ Value : "4", Condition : [{BM:"A"} ]}},{InletRating:{ Value : "150#", Condition : [{BM:"A"} ]}},{OutletSize:{ Value : "6", Condition : [{BM:"A"} ]}},{OutletRating:{ Value : "150#", Condition : [{BM:"A"} ]}},
        {InletSize:{ Value : "6", Condition : [{BM:"S"} ]}},{InletRating:{ Value : "150#", Condition : [{BM:"S"} ]}},{OutletSize:{ Value : "8", Condition : [{BM:"S"} ]}},{OutletRating:{ Value : "150#", Condition : [{BM:"S"} ]}},
        {InletSize:{ Value : "8", Condition : [{DC:"S"} ]}},{InletRating:{ Value : "150#", Condition : [{DC:"S"} ]}},{OutletSize:{ Value : "10", Condition : [{DC:"S"} ]}},{OutletRating:{ Value : "150#", Condition : [{DC:"S"} ]}},
        {InletSize:{ Value : "10", Condition : [{BTM:"A"} ]}},{InletRating:{ Value : "150#", Condition : [{BTM:"A"} ]}},{OutletSize:{ Value : "12", Condition : [{BTM:"A"} ]}},{OutletRating:{ Value : "150#", Condition : [{BTM:"A"} ]}},
        {InletSize:{ Value : "12", Condition : [{BTM:"S"} ]}},{InletRating:{ Value : "150#", Condition : [{BTM:"S"} ]}},{OutletSize:{ Value : "16", Condition : [{BTM:"S"} ]}},{OutletRating:{ Value : "150#", Condition : [{BTM:"S"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{BSG:"T"} ]}},{InletFinish:{ Value : "RFSF", Condition : [{BSG:"T"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{BSG:"T"} ]}},{OutletFinish:{ Value : "RFSF", Condition : [{BSG:"T"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{PBM:"A"} ]}},{InletFinish:{ Value : "RF", Condition : [{PBM:"A"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{PBM:"A"} ]}},{OutletFinish:{ Value : "RF", Condition : [{PBM:"A"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{PBM:"S"} ]}},{InletFinish:{ Value : "RFCS", Condition : [{PBM:"S"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{PBM:"S"} ]}},{OutletFinish:{ Value : "RFCS", Condition : [{PBM:"S"} ]}},
        {InletConn:{ Value : "Flngd.", Condition : [{PSG:"1"} ]}},{InletFinish:{ Value : "RFSF", Condition : [{PSG:"1"} ]}},{OutletConn:{ Value : "Flngd.", Condition : [{PSG:"1"} ]}},{OutletFinish:{ Value : "FF", Condition : [{PSG:"1"} ]}},
        {BodyBase:{ Value : "AL SB26-356-T6", Condition : [{PSG:"2"} ]}},{Nozzle:{ Value : "316 SST", Condition : [{PSG:"2"} ]}},
        {BodyBase:{ Value : "CS SA216-WCB", Condition : [{PSG:"3"} ]}},{Nozzle:{ Value : "316 SST", Condition : [{PSG:"3"} ]}},
        {BodyBase:{ Value : "SS SA351-CF8M", Condition : [{PSG:"4"} ]}},{Nozzle:{ Value : "316 SST", Condition : [{PSG:"4"} ]}},
        {CapCase:{ Value : "SS A240-304/316 (Single)", Condition : [{PSG:"5"} ]}},
        {Trim:{ Value : "AL", Condition : [{PSG:"6"} ]}},
        {Trim:{ Value : "SST (LP)", Condition : [{PSG:"7"} ]}},
        {Trim:{ Value : "SST (HP)", Condition : [{PSG:"8"} ]}},
        {Seat:{ Value : "FEP (Film)", Condition : [{PD:"B"} ]}},{SoftGoods:{ Value : "Teflon®", Condition : [{PD:"B"} ]}},
        {PressurePilotBody:{ Value : "AL 6061-T651", Condition : [{PD:"V"} ]}},
        {PressurePilotBody:{ Value : "SS A479-316/316L", Condition : [{PD:"E"} ]}},
        {Seat:{ Value : "Teflon®", Condition : [{PD:"T"} ]}},{SoftGoods:{ Value : "Teflon®", Condition : [{PD:"T"} ]}},
        {Seat:{ Value : "Buna-N", Condition : [{PS:"A"} ]}},{SoftGoods:{ Value : "Buna-N", Condition : [{PS:"A"} ]}},
        {Seat:{ Value : "Viton®", Condition : [{PS:"B"} ]}},{SoftGoods:{ Value : "Viton®", Condition : [{PS:"B"} ]}},
        {Seat:{ Value : "EPR", Condition : [{PS:"C"} ]}},{SoftGoods:{ Value : "EPR", Condition : [{PS:"C"} ]}},
        {Seat:{ Value : "Buna-N", Condition : [{PS:"D"} ]}},{SoftGoods:{ Value : "Buna-N", Condition : [{PS:"D"} ]}},
        {Seat:{ Value : "Viton®", Condition : [{PS:"E"} ]}},{SoftGoods:{ Value : "Viton®", Condition : [{PS:"E"} ]}},
        {Seat:{ Value : "EPR", Condition : [{PS:"F"} ]}},{SoftGoods:{ Value : "EPR", Condition : [{PS:"F"} ]}},
        {Seat:{ Value : "Kalrez®", Condition : [{PS:"G"} ]}},{SoftGoods:{ Value : "Kalrez®", Condition : [{PS:"G"} ]}},
        {Diaphragm:{ Value : "Hastelloy/Teflon®/304SST", Condition : [{PS:"H"} ]}},
        {Diaphragm:{ Value : "Buna-N", Condition : [{PS:"J"} ]}},
        {Diaphragm:{ Value : "Viton®", Condition : [{PS:"K"} ]}},
        {Diaphragm:{ Value : "EPR", Condition : [{PS:"2"} ]}},
        {Diaphragm:{ Value : "Teflon®", Condition : [{PS:"3"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"4"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"5"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"6"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"7"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PS:"8"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PBM:"A"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PBM:"S"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PSG:"1"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PSG:"2"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PSG:"3"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PSG:"4"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PSG:"5"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PSG:"6"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PSG:"7"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PSG:"8"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PD:"B"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PD:"V"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PD:"E"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PD:"T"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{VS:"A"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{VS:"B"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{VS:"C"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{VS:"D"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{ST:"S"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{ST:"E"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PA:"N"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PA:"A"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PA:"B"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{PA:"C"} ]}},
        {Body:{ Value : "AL 6061-T651", Condition : [{VAL1:"0"} ]}},
        {Body:{ Value : "SS A479-316/316L", Condition : [{VAL1:"1"} ]}},
        {Seat:{ Value : "Teflon®", Condition : [{VAL1:"2"} ]}},{SoftGoods:{ Value : "Teflon®", Condition : [{VAL1:"2"} ]}},
        {Seat:{ Value : "Buna-N", Condition : [{VAL2:"0"} ]}},{SoftGoods:{ Value : "Buna-N", Condition : [{VAL2:"0"} ]}},
        {Seat:{ Value : "Viton®", Condition : [{VAL2:"1"} ]}},{SoftGoods:{ Value : "Viton®", Condition : [{VAL2:"1"} ]}},
        {Seat:{ Value : "EPR", Condition : [{VAL2:"2"} ]}},{SoftGoods:{ Value : "EPR", Condition : [{VAL2:"2"} ]}},
        {Seat:{ Value : "Buna-N", Condition : [{VAL3:"0"} ]}},{SoftGoods:{ Value : "Buna-N", Condition : [{VAL3:"0"} ]}},
        {Seat:{ Value : "Viton®", Condition : [{VAL3:"1"} ]}},{SoftGoods:{ Value : "Viton®", Condition : [{VAL3:"1"} ]}},
        {Seat:{ Value : "EPR", Condition : [{VAL4:"0"} ]}},{SoftGoods:{ Value : "EPR", Condition : [{VAL4:"0"} ]}},
        {Diaphragm:{ Value : "Hastelloy/Teflon®/304SST", Condition : [{VAL4:"1"} ]}},
        {Diaphragm:{ Value : "Buna-N", Condition : [{VAL4:"2"} ]}},
        {Diaphragm:{ Value : "Viton®", Condition : [{VAL5:"0"} ]}},
        {Diaphragm:{ Value : "EPR", Condition : [{VAL5:"1"} ]}},
        {Diaphragm:{ Value : "Teflon®", Condition : [{VAL5:"2"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{VAL6:"0"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{VAL6:"1"} ]}},
        {Spring:{ Value : "316 SST", Condition : [{VAL6:"2"} ]}},
        {Spring:{ Value : "316 SST", Condition : [ ]}},
        {Spring:{ Value : "316 SST", Condition : [ ]}},
        {Spring:{ Value : "316 SST", Condition : [ ]}},
        {Spring:{ Value : "316 SST", Condition : [ ]}},
        {Spring:{ Value : "316 SST", Condition : [ ]}},
        {Spring:{ Value : "316 SST", Condition : [ ]}},
        {Spring:{ Value : "316 SST", Condition : [ ]}},
        {Spring:{ Value : "316 SST", Condition : [ ]}},
        {Spring:{ Value : "316 SST", Condition : [ ]}},
        {Accessory1:{ Value : "Integral Sense", Condition : [ ]}},
        {Accessory1:{ Value : "Remote Sense Connect.", Condition : [ ]}},
        
        {Accessory1:{ Value : "Flame Screen", Condition : [ ]}},
        {Accessory1:{ Value : "Incoloy Studs and Nutes", Condition : [ ]}},
        {Accessory1:{ Value : "SS Cert CaseBlts,Stds,Nts", Condition : [ ]}},
        
        {Accessory1:{ Value : "Pilot Gag", Condition : [ ]}},
        {Accessory1:{ Value : "Lift Lever", Condition : [ ]}},
        {Accessory1:{ Value : "Pilot Gag", Condition : [ ]}},{Accessory2:{ Value : "Lift Lever", Condition : [ ]}},
        {Accessory1:{ Value : "Pilot Aux. Adapter", Condition : [ ]}},
        {Accessory1:{ Value : "Aux. Setter A", Condition : [ ]}},
        {Accessory1:{ Value : "Aux. Setters A & B", Condition : [ ]}},
        {Accessory1:{ Value : "Aux. Setters A, B, & C", Condition : [ ]}},
        
        {Accessory1:{ Value : "SS 3-Way Ball Valve", Condition : [ ]}},
        {Accessory1:{ Value : "SS 3Way Bll Vlv w/ Lck Tb", Condition : [ ]}},
        
        {Accessory1:{ Value : "SS Hand Vlv & Check Vlv", Condition : [ ]}},
        {Accessory1:{ Value : "AL Hand Vlv & Check Vlv", Condition : [ ]}},
        
        {Accessory1:{ Value : "SS Manual Blowdown", Condition : [ ]}},
        
        {Accessory1:{ Value : "SS Manual Unloader", Condition : [ ]}},
        {Accessory1:{ Value : "Remote Unloader", Condition : [ ]}},
        
        {Accessory1:{ Value : "SS Aux. Filter w/ Drain", Condition : [ ]}},
        {Accessory1:{ Value : "CS Aux. Filter w/ Drain", Condition : [ ]}},
        
        {Accessory1:{ Value : "SS Back Flow Preventer", Condition : [ ]}},
        {Accessory1:{ Value : "AL Back Flow Preventer", Condition : [ ]}},
        {Accessory1:{ Value : "Pilot Exhaust to Atm.", Condition : [ ]}},
        {Accessory1:{ Value : "Pilot Exhaust to MV Out.", Condition : [ ]}}
        
        ]}
        
]

module.exports = {
    lowPres_APOAPO
}