const tankVent_96A = [
    {ModelId:"96A", Data:[
        {ValveType:{ Value : "Vacuum Breaker - Top Mounted", Condition : [{MOD:"96A"} ]}},
        {InletSize:{ Value : "Open", Condition : [{IS:"04"} ]}},{InletConn:{ Value : "To", Condition : [{IS:"04"} ]}},{InletRating:{ Value : "Atm.", Condition : [{IS:"04"} ]}},{OutletSize:{ Value : "4", Condition : [{IS:"04"} ]}},
        {InletSize:{ Value : "Open", Condition : [{IS:"06"} ]}},{InletConn:{ Value : "To", Condition : [{IS:"06"} ]}},{InletRating:{ Value : "Atm.", Condition : [{IS:"06"} ]}},{OutletSize:{ Value : "6", Condition : [{IS:"06"} ]}},
        {InletSize:{ Value : "Open", Condition : [{IS:"08"} ]}},{InletConn:{ Value : "To", Condition : [{IS:"08"} ]}},{InletRating:{ Value : "Atm.", Condition : [{IS:"08"} ]}},{OutletSize:{ Value : "8", Condition : [{IS:"08"} ]}},
        {InletSize:{ Value : "Open", Condition : [{IS:"12"} ]}},{InletConn:{ Value : "To", Condition : [{IS:"12"} ]}},{InletRating:{ Value : "Atm.", Condition : [{IS:"12"} ]}},{OutletSize:{ Value : "12", Condition : [{IS:"12"} ]}},
        {InletSize:{ Value : "Open", Condition : [{IS:"16"} ]}},{InletConn:{ Value : "To", Condition : [{IS:"16"} ]}},{InletRating:{ Value : "Atm.", Condition : [{IS:"16"} ]}},{OutletSize:{ Value : "16", Condition : [{IS:"16"} ]}},
        {OutletConn:{ Value : "150#", Condition : [{TC:"R"} ]}},{OutletRating:{ Value : "RF", Condition : [{TC:"R"} ]}},{OutletFinish:{ Value : "Flngd.", Condition : [{TC:"R"} ]}},{Standard:{ Value : "ASME B16.5", Condition : [{TC:"R"} ]}},
        {OutletConn:{ Value : "150#", Condition : [{TC:"F"} ]}},{OutletRating:{ Value : "FF", Condition : [{TC:"F"} ]}},{OutletFinish:{ Value : "Flngd.", Condition : [{TC:"F"} ]}},
        {Body:{ Value : "AL ASTM-B26 356-T6", Condition : [{MVM:"A"} ]}},{SeatRing:{ Value : "AL 6061-T6", Condition : [{MVM:"A"} ]}},{GuideTube:{ Value : "SS A269-316W/D", Condition : [{MVM:"A"} ]}},{GuideRod:{ Value : "303 SS Teflon Coated", Condition : [{MVM:"A"} ]}},{SeatPlate:{ Value : "SS A240-316", Condition : [{MVM:"A"} ]}},{InletScreen:{ Value : "304 SS, 1'' Mesh", Condition : [{MVM:"A"} ]}},{SeatRingRetainer:{ Value : "SS A240-316", Condition : [{MVM:"A"} ]}},{RetainerBolts:{ Value : "SS 18-8", Condition : [{MVM:"A"} ]}},
        {Body:{ Value : "CS SA216-WCC", Condition : [{IS:"04"},{MVM:"C"} ]}},{SeatRing:{ Value : "SS A240-316", Condition : [{IS:"04"},{MVM:"C"} ]}},{GuideTube:{ Value : "SS A269-316W/D", Condition : [{IS:"04"},{MVM:"C"} ]}},{GuideRod:{ Value : "303 SS Teflon Coated", Condition : [{IS:"04"},{MVM:"C"} ]}},{SeatPlate:{ Value : "SS A240-316", Condition : [{IS:"04"},{MVM:"C"} ]}},{InletScreen:{ Value : "304 SS, 1'' Mesh", Condition : [{IS:"04"},{MVM:"C"} ]}},{SeatRingRetainer:{ Value : "SS A240-316", Condition : [{IS:"04"},{MVM:"C"} ]}},{RetainerBolts:{ Value : "SS 18-8", Condition : [{IS:"04"},{MVM:"C"} ]}},
        {Body:{ Value : "CS SA216-WCB", Condition : [{IS:"06"},{MVM:"C"} ]}},{SeatRing:{ Value : "SS A240-316", Condition : [{IS:"06"},{MVM:"C"} ]}},{GuideTube:{ Value : "SS A269-316W/D", Condition : [{IS:"06"},{MVM:"C"} ]}},{GuideRod:{ Value : "303 SS Teflon Coated", Condition : [{IS:"06"},{MVM:"C"} ]}},{SeatPlate:{ Value : "SS A240-316", Condition : [{IS:"06"},{MVM:"C"} ]}},{InletScreen:{ Value : "304 SS, 1'' Mesh", Condition : [{IS:"06"},{MVM:"C"} ]}},{SeatRingRetainer:{ Value : "SS A240-316", Condition : [{IS:"06"},{MVM:"C"} ]}},{RetainerBolts:{ Value : "SS 18-8", Condition : [{IS:"06"},{MVM:"C"} ]}},
        {Body:{ Value : "CS SA216-WCB", Condition : [{IS:"08"},{MVM:"C"} ]}},{SeatRing:{ Value : "SS A240-316", Condition : [{IS:"08"},{MVM:"C"} ]}},{GuideTube:{ Value : "SS A269-316W/D", Condition : [{IS:"08"},{MVM:"C"} ]}},{GuideRod:{ Value : "303 SS Teflon Coated", Condition : [{IS:"08"},{MVM:"C"} ]}},{SeatPlate:{ Value : "SS A240-316", Condition : [{IS:"08"},{MVM:"C"} ]}},{InletScreen:{ Value : "304 SS, 1'' Mesh", Condition : [{IS:"08"},{MVM:"C"} ]}},{SeatRingRetainer:{ Value : "SS A240-316", Condition : [{IS:"08"},{MVM:"C"} ]}},{RetainerBolts:{ Value : "SS 18-8", Condition : [{IS:"08"},{MVM:"C"} ]}},
        {Body:{ Value : "CS SA216-WCB", Condition : [{IS:"12"},{MVM:"C"} ]}},{SeatRing:{ Value : "SS A240-316", Condition : [{IS:"12"},{MVM:"C"} ]}},{GuideTube:{ Value : "SS A269-316W/D", Condition : [{IS:"12"},{MVM:"C"} ]}},{GuideRod:{ Value : "303 SS Teflon Coated", Condition : [{IS:"12"},{MVM:"C"} ]}},{SeatPlate:{ Value : "SS A240-316", Condition : [{IS:"12"},{MVM:"C"} ]}},{InletScreen:{ Value : "304 SS, 1'' Mesh", Condition : [{IS:"12"},{MVM:"C"} ]}},{SeatRingRetainer:{ Value : "SS A240-316", Condition : [{IS:"12"},{MVM:"C"} ]}},{RetainerBolts:{ Value : "SS 18-8", Condition : [{IS:"12"},{MVM:"C"} ]}},
        {Body:{ Value : "CS SA216-WCB", Condition : [{IS:"16"},{MVM:"C"} ]}},{SeatRing:{ Value : "SS A240-316", Condition : [{IS:"16"},{MVM:"C"} ]}},{GuideTube:{ Value : "SS A269-316W/D", Condition : [{IS:"16"},{MVM:"C"} ]}},{GuideRod:{ Value : "303 SS Teflon Coated", Condition : [{IS:"16"},{MVM:"C"} ]}},{SeatPlate:{ Value : "SS A240-316", Condition : [{IS:"16"},{MVM:"C"} ]}},{InletScreen:{ Value : "304 SS, 1'' Mesh", Condition : [{IS:"16"},{MVM:"C"} ]}},{SeatRingRetainer:{ Value : "SS A240-316", Condition : [{IS:"16"},{MVM:"C"} ]}},{RetainerBolts:{ Value : "SS 18-8", Condition : [{IS:"16"},{MVM:"C"} ]}},
        {Body:{ Value : "SS A351-CF8M", Condition : [{MVM:"S"} ]}},{SeatRing:{ Value : "SS A240-316", Condition : [{MVM:"S"} ]}},{GuideTube:{ Value : "SS A269-316W/D", Condition : [{MVM:"S"} ]}},{GuideRod:{ Value : "303 SS Teflon Coated", Condition : [{MVM:"S"} ]}},{SeatPlate:{ Value : "SS A240-316", Condition : [{MVM:"S"} ]}},{InletScreen:{ Value : "304 SS, 1'' Mesh", Condition : [{MVM:"S"} ]}},{SeatRingRetainer:{ Value : "SS A240-316", Condition : [{MVM:"S"} ]}},{RetainerBolts:{ Value : "SS 18-8", Condition : [{MVM:"S"} ]}},
        {Seat:{ Value : "Buna-N", Condition : [{SG:"B"} ]}},
        {Seat:{ Value : "Viton ", Condition : [{SG:"V"} ]}},
        {Seat:{ Value : "EPR", Condition : [{SG:"E"} ]}},
        {PressureReliefConnectionSize:{ Value : "Capped", Condition : [{MVM:"A"},{PRC:"CP"} ]}},{FlangeCap:{ Value : "AL 6061-T6", Condition : [{MVM:"A"},{PRC:"CP"} ]}},{FlangeStudNut:{ Value : "316 SS / 18-8 SS", Condition : [{MVM:"A"},{PRC:"CP"} ]}},{Gaskets:{ Value : "Teflon", Condition : [{MVM:"A"},{PRC:"CP"} ]}},
        {PressureReliefConnectionSize:{ Value : "Capped", Condition : [{MVM:"C"},{PRC:"CP"} ]}},{FlangeCap:{ Value : "SS A240-316", Condition : [{MVM:"C"},{PRC:"CP"} ]}},{FlangeStudNut:{ Value : "316 SS / 18-8 SS", Condition : [{MVM:"C"},{PRC:"CP"} ]}},{Gaskets:{ Value : "Teflon", Condition : [{MVM:"C"},{PRC:"CP"} ]}},
        {PressureReliefConnectionSize:{ Value : "Capped", Condition : [{MVM:"S"},{PRC:"CP"} ]}},{FlangeCap:{ Value : "SS A240-316", Condition : [{MVM:"S"},{PRC:"CP"} ]}},{FlangeStudNut:{ Value : "316 SS / 18-8 SS", Condition : [{MVM:"S"},{PRC:"CP"} ]}},{Gaskets:{ Value : "Teflon", Condition : [{MVM:"S"},{PRC:"CP"} ]}},
        {PressureReliefConnectionSize:{ Value : '3"', Condition : [{PRC:"03"} ]}},{FlangeCap:{ Value : "n/a", Condition : [{PRC:"03"} ]}},{FlangeStudNut:{ Value : "n/a", Condition : [{PRC:"03"} ]}},{Gaskets:{ Value : "n/a", Condition : [{PRC:"03"} ]}},
        {PressureReliefConnectionSize:{ Value : '4"', Condition : [{PRC:"04"} ]}},{FlangeCap:{ Value : "n/a", Condition : [{PRC:"04"} ]}},{FlangeStudNut:{ Value : "n/a", Condition : [{PRC:"04"} ]}},{Gaskets:{ Value : "n/a", Condition : [{PRC:"04"} ]}},
        {PressureReliefConnectionSize:{ Value : '6"', Condition : [{PRC:"06"} ]}},{FlangeCap:{ Value : "n/a", Condition : [{PRC:"06"} ]}},{FlangeStudNut:{ Value : "n/a", Condition : [{PRC:"06"} ]}},{Gaskets:{ Value : "n/a", Condition : [{PRC:"06"} ]}},
        {PressureReliefConnectionSize:{ Value : '8"', Condition : [{PRC:"08"} ]}},{FlangeCap:{ Value : "n/a", Condition : [{PRC:"08"} ]}},{FlangeStudNut:{ Value : "n/a", Condition : [{PRC:"08"} ]}},{Gaskets:{ Value : "n/a", Condition : [{PRC:"08"} ]}},
        {PressureReliefConnectionSize:{ Value : '10"', Condition : [{PRC:"10"} ]}},{FlangeCap:{ Value : "n/a", Condition : [{PRC:"10"} ]}},{FlangeStudNut:{ Value : "n/a", Condition : [{PRC:"10"} ]}},{Gaskets:{ Value : "n/a", Condition : [{PRC:"10"} ]}},
        {PressureReliefConnectionSize:{ Value : '12"', Condition : [{PRC:"12"} ]}},{FlangeCap:{ Value : "n/a", Condition : [{PRC:"12"} ]}},{FlangeStudNut:{ Value : "n/a", Condition : [{PRC:"12"} ]}},{Gaskets:{ Value : "n/a", Condition : [{PRC:"12"} ]}},
        {PressureReliefConnectionSize:{ Value : '16"', Condition : [{PRC:"16"} ]}},{FlangeCap:{ Value : "n/a", Condition : [{PRC:"16"} ]}},{FlangeStudNut:{ Value : "n/a", Condition : [{PRC:"16"} ]}},{Gaskets:{ Value : "n/a", Condition : [{PRC:"16"} ]}},
        {Nace:{ Value : "No", Condition : [{NACE:"N"} ]}},
        {Nace:{ Value : "NACE MR0175, 2002 Ed.", Condition : [{NACE:"Y"} ]}},
        {LOXCleaned:{ Value : "No", Condition : [{SER:"A"} ]}},
        {LOXCleaned:{ Value : "Yes", Condition : [{SER:"B"} ]}}
        ]}
]

module.exports = {
    tankVent_96A
};