const tankVent = [
    {ModelId:"2010B", Data :[
        {ValveType:{ Value : "Weight Loaded Tank Vent - Vent to Atm.", Condition : [{ST1:"201"} ]}},{Spring:{ Value : "N/A", Condition : [{ST1:"201"} ]}},
        {InletSize:{ Value : "2", Condition : [{SZ:"2"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"2"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"2"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"2"} ]}},
        {InletSize:{ Value : "3", Condition : [{SZ:"3"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"3"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"3"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"3"} ]}},
        {InletSize:{ Value : "4", Condition : [{SZ:"4"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"4"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"4"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"4"} ]}},
        {InletSize:{ Value : "6", Condition : [{SZ:"6"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"6"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"6"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"6"} ]}},
        {InletSize:{ Value : "8", Condition : [{SZ:"8"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"8"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"8"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"8"} ]}},
        {InletSize:{ Value : "10", Condition : [{SZ:"0"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"0"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"0"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"0"} ]}},
        {InletSize:{ Value : "12", Condition : [{SZ:"1"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"1"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"1"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"1"} ]}},
        {InletConn:{ Value : "FF", Condition : [{FF:"F"} ]}},
        {InletConn:{ Value : "RF", Condition : [{FF:"R"} ]}},
        {InletRating:{ Value : "150#", Condition : [{FD:"F"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{FD:"F"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{FD:"F"} ]}},
        {InletRating:{ Value : "150#", Condition : [{FD:"M"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{FD:"M"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{FD:"M"} ]}},
        {InletRating:{ Value : "PN16", Condition : [{FD:"D"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{FD:"D"} ]}},{Standard:{ Value : "DIN", Condition : [{FD:"D"} ]}},
        {Body:{ Value : "Aluminum", Condition : [{BT:"1"} ]}},{Trim:{ Value : "Aluminum", Condition : [{BT:"1"} ]}},
        {Body:{ Value : "Aluminum", Condition : [{BT:"2"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"2"} ]}},
        {Body:{ Value : "Carbon Steel", Condition : [{BT:"3"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"3"} ]}},
        {Body:{ Value : "316 SST", Condition : [{BT:"4"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"4"} ]}},
        {Body:{ Value : "Ductile Iron", Condition : [{BT:"5"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"5"} ]}},
        {Body:{ Value : "Carbon Steel", Condition : [{BT:"7"} ]}},{Trim:{ Value : "316SST/AL-Tef Ctd Vac Pallet", Condition : [{BT:"7"} ]}},
        {Body:{ Value : "316 SST", Condition : [{BT:"8"} ]}},{Trim:{ Value : "316SST/AL-Tef Ctd Vac Pallet", Condition : [{BT:"8"} ]}},
        {TrimCoating:{ Value : "None", Condition : [{TC:"0"} ]}},
        {TrimCoating:{ Value : "All Weather Coating", Condition : [{TC:"1"} ]}},
        {Insert:{ Value : "Teflon®", Condition : [{IN:"T"} ]}},
        {Insert:{ Value : "Buna-N", Condition : [{IN:"B"} ]}},
        {Insert:{ Value : "Viton®", Condition : [{IN:"V"} ]}},
        {Gaskets:{ Value : "Fiber", Condition : [{GK:"O"} ]}},{O_ring:{ Value : "Buna-N", Condition : [{GK:"O"} ]}},
        {Gaskets:{ Value : "Teflon®", Condition : [{GK:"T"} ]}},{O_ring:{ Value : "Teflon®", Condition : [{GK:"T"} ]}},
        {Gaskets:{ Value : "Buna-N", Condition : [{GK:"B"} ]}},{O_ring:{ Value : "Buna-N", Condition : [{GK:"B"} ]}},
        {Gaskets:{ Value : "Viton®", Condition : [{GK:"V"} ]}},{O_ring:{ Value : "Viton®", Condition : [{GK:"V"} ]}},
        {Screen:{ Value : "Plastic", Condition : [{SR:"P"} ]}},{Retainer:{ Value : "Plastic", Condition : [{SR:"P"} ]}},
        {Screen:{ Value : "304 SST", Condition : [{SR:"S"} ]}},{Retainer:{ Value : "316 SST", Condition : [{SR:"S"} ]}},
        {PressureRange:{ Value : "Low Pressure Setting", Condition : [{RP:"02"} ]}},
        {PressureRange:{ Value : "High Pressure Setting", Condition : [{RP:"04"} ]}},
        {VacuumRange:{ Value : "Low Pressure Setting", Condition : [{RV:"02"} ]}},
        {VacuumRange:{ Value : "High Pressure Setting", Condition : [{RV:"04"} ]}}
        
        ]},
        
        {ModelId:"5000", Data :[
        {EndHousing:{ Value : "Aluminum", Condition : [{HB:"1"} ]}},{CoreHousingFrame:{ Value : "Aluminum", Condition : [{HB:"1"} ]}},{ElementSheets:{ Value : "Aluminum", Condition : [{HB:"1"} ]}},
        {EndHousing:{ Value : "Aluminum", Condition : [{HB:"2"} ]}},{CoreHousingFrame:{ Value : "316 SST", Condition : [{HB:"2"} ]}},{ElementSheets:{ Value : "316 SST", Condition : [{HB:"2"} ]}},
        {EndHousing:{ Value : "Carbon Steel", Condition : [{HB:"3"} ]}},{CoreHousingFrame:{ Value : "316 SST", Condition : [{HB:"3"} ]}},{ElementSheets:{ Value : "316 SST", Condition : [{HB:"3"} ]}},
        {EndHousing:{ Value : "316 SST", Condition : [{HB:"6"} ]}},{CoreHousingFrame:{ Value : "316 SST", Condition : [{HB:"6"} ]}},{ElementSheets:{ Value : "316 SST", Condition : [{HB:"6"} ]}},
        {Hardware:{ Value : "Zn Plated Carbon Stl.", Condition : [{HB:"1"},{HW:"-"} ]}},
        {Hardware:{ Value : "Zn Plated Carbon Stl.", Condition : [{HB:"2"},{HW:"-"} ]}},
        {Hardware:{ Value : "Zn Plated Carbon Stl.", Condition : [{HB:"3"},{HW:"-"} ]}},
        {Hardware:{ Value : "304 SST", Condition : [{HB:"6"},{HW:"-"} ]}},
        {Hardware:{ Value : "316SST", Condition : [{HW:"S"} ]}}
        ]},
        
        {ModelId:"2020B", Data :[
        {ValveType:{ Value : "Weight Loaded Tank Vent - Pipe Away", Condition : [{ST1:"202"} ]}},{Spring:{ Value : "N/A", Condition : [{ST1:"202"} ]}},
        {InletSize:{ Value : "2", Condition : [{SZ:"2"} ]}},{OutletSize:{ Value : "3", Condition : [{SZ:"2"} ]}},
        {InletSize:{ Value : "3", Condition : [{SZ:"3"} ]}},{OutletSize:{ Value : "4", Condition : [{SZ:"3"} ]}},
        {InletSize:{ Value : "4", Condition : [{SZ:"4"} ]}},{OutletSize:{ Value : "6", Condition : [{SZ:"4"} ]}},
        {InletSize:{ Value : "6", Condition : [{SZ:"6"} ]}},{OutletSize:{ Value : "8", Condition : [{SZ:"6"} ]}},
        {InletSize:{ Value : "8", Condition : [{SZ:"8"} ]}},{OutletSize:{ Value : "10", Condition : [{SZ:"8"} ]}},
        {InletSize:{ Value : "10", Condition : [{SZ:"0"} ]}},{OutletSize:{ Value : "12", Condition : [{SZ:"0"} ]}},
        {InletSize:{ Value : "12", Condition : [{SZ:"1"} ]}},{OutletSize:{ Value : "14", Condition : [{SZ:"1"} ]}},
        {InletConn:{ Value : "FF", Condition : [{FF:"F"} ]}},{OutletConn:{ Value : "FF", Condition : [{FF:"F"} ]}},
        {InletConn:{ Value : "RF", Condition : [{FF:"R"} ]}},{OutletConn:{ Value : "RF", Condition : [{FF:"R"} ]}},
        {InletRating:{ Value : "150#", Condition : [{FD:"F"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{FD:"F"} ]}},{OutletRating:{ Value : "150#", Condition : [{FD:"F"} ]}},{OutletFinish:{ Value : "Drilling", Condition : [{FD:"F"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{FD:"F"} ]}},
        {InletRating:{ Value : "150#", Condition : [{FD:"M"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{FD:"M"} ]}},{OutletRating:{ Value : "150#", Condition : [{FD:"M"} ]}},{OutletFinish:{ Value : "Drilling", Condition : [{FD:"M"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{FD:"M"} ]}},
        {InletRating:{ Value : "PN16", Condition : [{FD:"D"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{FD:"D"} ]}},{OutletRating:{ Value : "PN16", Condition : [{FD:"D"} ]}},{OutletFinish:{ Value : "Drilling", Condition : [{FD:"D"} ]}},{Standard:{ Value : "DIN", Condition : [{FD:"D"} ]}},
        {Body:{ Value : "Aluminum", Condition : [{BT:"1"} ]}},{Trim:{ Value : "Aluminum", Condition : [{BT:"1"} ]}},
        {Body:{ Value : "Aluminum", Condition : [{BT:"2"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"2"} ]}},
        {Body:{ Value : "Carbon Steel", Condition : [{BT:"3"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"3"} ]}},
        {Body:{ Value : "316 SST", Condition : [{BT:"4"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"4"} ]}},
        {Body:{ Value : "Ductile Iron", Condition : [{BT:"5"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"5"} ]}},
        {Body:{ Value : "Carbon Steel", Condition : [{BT:"7"} ]}},{Trim:{ Value : "316SST/AL-Tef Ctd Vac Pallet", Condition : [{BT:"7"} ]}},
        {Body:{ Value : "316 SST", Condition : [{BT:"8"} ]}},{Trim:{ Value : "316SST/AL-Tef Ctd Vac Pallet", Condition : [{BT:"8"} ]}},
        {TrimCoating:{ Value : "None", Condition : [{TC:"0"} ]}},
        {TrimCoating:{ Value : "All Weather Coating", Condition : [{TC:"1"} ]}},
        {Insert:{ Value : "Teflon®", Condition : [{IN:"T"} ]}},
        {Insert:{ Value : "Buna-N", Condition : [{IN:"B"} ]}},
        {Insert:{ Value : "Viton®", Condition : [{IN:"V"} ]}},
        {Gaskets:{ Value : "Fiber", Condition : [{GK:"O"} ]}},{O_ring:{ Value : "Buna-N", Condition : [{GK:"O"} ]}},
        {Gaskets:{ Value : "Teflon®", Condition : [{GK:"T"} ]}},{O_ring:{ Value : "Teflon®", Condition : [{GK:"T"} ]}},
        {Gaskets:{ Value : "Buna-N", Condition : [{GK:"B"} ]}},{O_ring:{ Value : "Buna-N", Condition : [{GK:"B"} ]}},
        {Gaskets:{ Value : "Viton®", Condition : [{GK:"V"} ]}},{O_ring:{ Value : "Viton®", Condition : [{GK:"V"} ]}},
        {Screen:{ Value : "Plastic", Condition : [{SR:"P"} ]}},{Retainer:{ Value : "Plastic", Condition : [{SR:"P"} ]}},
        {Screen:{ Value : "304 SST", Condition : [{SR:"S"} ]}},{Retainer:{ Value : "316 SST", Condition : [{SR:"S"} ]}},
        {PressureRange:{ Value : "Low Pressure Setting", Condition : [{RP:"02"} ]}},
        {PressureRange:{ Value : "High Pressure Setting", Condition : [{RP:"04"} ]}},
        {VacuumRange:{ Value : "Low Pressure Setting", Condition : [{RV:"02"} ]}},
        {VacuumRange:{ Value : "High Pressure Setting", Condition : [{RV:"04"} ]}}
        ]},
        
        {ModelId:"3500B", Data :[
        {ValveType:{ Value : "Weight Loaded Tank Vent - Top Mounted", Condition : [{ST1:"350"} ]}},{PressureRange:{ Value : "N/A", Condition : [{ST1:"350"} ]}},{Spring:{ Value : "N/A", Condition : [{ST1:"350"} ]}},
        {InletSize:{ Value : "Open", Condition : [{SZ:"2"} ]}},{InletConn:{ Value : "To", Condition : [{SZ:"2"} ]}},{InletRating:{ Value : "Atm.", Condition : [{SZ:"2"} ]}},{OutletSize:{ Value : "2", Condition : [{SZ:"2"} ]}},
        {InletSize:{ Value : "Open", Condition : [{SZ:"3"} ]}},{InletConn:{ Value : "To", Condition : [{SZ:"3"} ]}},{InletRating:{ Value : "Atm.", Condition : [{SZ:"3"} ]}},{OutletSize:{ Value : "3", Condition : [{SZ:"3"} ]}},
        {InletSize:{ Value : "Open", Condition : [{SZ:"4"} ]}},{InletConn:{ Value : "To", Condition : [{SZ:"4"} ]}},{InletRating:{ Value : "Atm.", Condition : [{SZ:"4"} ]}},{OutletSize:{ Value : "4", Condition : [{SZ:"4"} ]}},
        {InletSize:{ Value : "Open", Condition : [{SZ:"6"} ]}},{InletConn:{ Value : "To", Condition : [{SZ:"6"} ]}},{InletRating:{ Value : "Atm.", Condition : [{SZ:"6"} ]}},{OutletSize:{ Value : "6", Condition : [{SZ:"6"} ]}},
        {InletSize:{ Value : "Open", Condition : [{SZ:"8"} ]}},{InletConn:{ Value : "To", Condition : [{SZ:"8"} ]}},{InletRating:{ Value : "Atm.", Condition : [{SZ:"8"} ]}},{OutletSize:{ Value : "8", Condition : [{SZ:"8"} ]}},
        {InletSize:{ Value : "Open", Condition : [{SZ:"0"} ]}},{InletConn:{ Value : "To", Condition : [{SZ:"0"} ]}},{InletRating:{ Value : "Atm.", Condition : [{SZ:"0"} ]}},{OutletSize:{ Value : "10", Condition : [{SZ:"0"} ]}},
        {InletSize:{ Value : "Open", Condition : [{SZ:"1"} ]}},{InletConn:{ Value : "To", Condition : [{SZ:"1"} ]}},{InletRating:{ Value : "Atm.", Condition : [{SZ:"1"} ]}},{OutletSize:{ Value : "12", Condition : [{SZ:"1"} ]}},
        {OutletConn:{ Value : "FF", Condition : [{FF:"F"} ]}},
        {OutletConn:{ Value : "RF", Condition : [{FF:"R"} ]}},
        {OutletRating:{ Value : "150#", Condition : [{FD:"F"} ]}},{OutletFinish:{ Value : "Drilling", Condition : [{FD:"F"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{FD:"F"} ]}},
        {OutletRating:{ Value : "150#", Condition : [{FD:"M"} ]}},{OutletFinish:{ Value : "Drilling", Condition : [{FD:"M"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{FD:"M"} ]}},
        {OutletRating:{ Value : "PN16", Condition : [{FD:"D"} ]}},{OutletFinish:{ Value : "Drilling", Condition : [{FD:"D"} ]}},{Standard:{ Value : "DIN", Condition : [{FD:"D"} ]}},
        {Body:{ Value : "Aluminum", Condition : [{BT:"1"} ]}},{Trim:{ Value : "Aluminum", Condition : [{BT:"1"} ]}},
        {Body:{ Value : "Aluminum", Condition : [{BT:"2"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"2"} ]}},
        {Body:{ Value : "Carbon Steel", Condition : [{BT:"3"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"3"} ]}},
        {Body:{ Value : "316 SST", Condition : [{BT:"4"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"4"} ]}},
        {Body:{ Value : "Ductile Iron", Condition : [{BT:"5"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"5"} ]}},
        {Body:{ Value : "Carbon Steel", Condition : [{BT:"7"} ]}},{Trim:{ Value : "316SST/AL-Tef Ctd Vac Pallet", Condition : [{BT:"7"} ]}},
        {Body:{ Value : "316 SST", Condition : [{BT:"8"} ]}},{Trim:{ Value : "316SST/AL-Tef Ctd Vac Pallet", Condition : [{BT:"8"} ]}},
        {TrimCoating:{ Value : "None", Condition : [{TC:"0"} ]}},
        {TrimCoating:{ Value : "All Weather Coating", Condition : [{TC:"1"} ]}},
        {Insert:{ Value : "Teflon®", Condition : [{IN:"T"} ]}},
        {Insert:{ Value : "Buna-N", Condition : [{IN:"B"} ]}},
        {Insert:{ Value : "Viton®", Condition : [{IN:"V"} ]}},
        {Gaskets:{ Value : "Fiber", Condition : [{GK:"O"} ]}},{O_ring:{ Value : "Buna-N", Condition : [{GK:"O"} ]}},
        {Gaskets:{ Value : "Teflon®", Condition : [{GK:"T"} ]}},{O_ring:{ Value : "Teflon®", Condition : [{GK:"T"} ]}},
        {Gaskets:{ Value : "Buna-N", Condition : [{GK:"B"} ]}},{O_ring:{ Value : "Buna-N", Condition : [{GK:"B"} ]}},
        {Gaskets:{ Value : "Viton®", Condition : [{GK:"V"} ]}},{O_ring:{ Value : "Viton®", Condition : [{GK:"V"} ]}},
        {Screen:{ Value : "Plastic", Condition : [{SR:"P"} ]}},{Retainer:{ Value : "Plastic", Condition : [{SR:"P"} ]}},
        {Screen:{ Value : "304 SST", Condition : [{SR:"S"} ]}},{Retainer:{ Value : "316 SST", Condition : [{SR:"S"} ]}},
        {VacuumRange:{ Value : "Low Vacuum Setting", Condition : [{RG:"02"} ]}},
        {VacuumRange:{ Value : "High Vacuum Setting", Condition : [{RG:"04"} ]}}
        ]},
        {ModelId:"3600B", Data :[
        {ValveType:{ Value : "Weight Loaded Tank Vent - Side Mounted", Condition : [{ST1:"360"} ]}},{PressureRange:{ Value : "N/A", Condition : [{ST1:"360"} ]}},{Spring:{ Value : "N/A", Condition : [{ST1:"360"} ]}},
        {InletSize:{ Value : "Open", Condition : [{SZ:"2"} ]}},{InletConn:{ Value : "To", Condition : [{SZ:"2"} ]}},{InletRating:{ Value : "Atm.", Condition : [{SZ:"2"} ]}},{OutletSize:{ Value : "2", Condition : [{SZ:"2"} ]}},
        {InletSize:{ Value : "Open", Condition : [{SZ:"3"} ]}},{InletConn:{ Value : "To", Condition : [{SZ:"3"} ]}},{InletRating:{ Value : "Atm.", Condition : [{SZ:"3"} ]}},{OutletSize:{ Value : "3", Condition : [{SZ:"3"} ]}},
        {InletSize:{ Value : "Open", Condition : [{SZ:"4"} ]}},{InletConn:{ Value : "To", Condition : [{SZ:"4"} ]}},{InletRating:{ Value : "Atm.", Condition : [{SZ:"4"} ]}},{OutletSize:{ Value : "4", Condition : [{SZ:"4"} ]}},
        {InletSize:{ Value : "Open", Condition : [{SZ:"6"} ]}},{InletConn:{ Value : "To", Condition : [{SZ:"6"} ]}},{InletRating:{ Value : "Atm.", Condition : [{SZ:"6"} ]}},{OutletSize:{ Value : "6", Condition : [{SZ:"6"} ]}},
        {InletSize:{ Value : "Open", Condition : [{SZ:"8"} ]}},{InletConn:{ Value : "To", Condition : [{SZ:"8"} ]}},{InletRating:{ Value : "Atm.", Condition : [{SZ:"8"} ]}},{OutletSize:{ Value : "8", Condition : [{SZ:"8"} ]}},
        {InletSize:{ Value : "Open", Condition : [{SZ:"0"} ]}},{InletConn:{ Value : "To", Condition : [{SZ:"0"} ]}},{InletRating:{ Value : "Atm.", Condition : [{SZ:"0"} ]}},{OutletSize:{ Value : "10", Condition : [{SZ:"0"} ]}},
        {InletSize:{ Value : "Open", Condition : [{SZ:"1"} ]}},{InletConn:{ Value : "To", Condition : [{SZ:"1"} ]}},{InletRating:{ Value : "Atm.", Condition : [{SZ:"1"} ]}},{OutletSize:{ Value : "12", Condition : [{SZ:"1"} ]}},
        {OutletConn:{ Value : "FF", Condition : [{FF:"F"} ]}},
        {OutletConn:{ Value : "RF", Condition : [{FF:"R"} ]}},
        {OutletRating:{ Value : "150#", Condition : [{FD:"F"} ]}},{OutletFinish:{ Value : "Drilling", Condition : [{FD:"F"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{FD:"F"} ]}},
        {OutletRating:{ Value : "PN16", Condition : [{FD:"D"} ]}},{OutletFinish:{ Value : "Drilling", Condition : [{FD:"D"} ]}},{Standard:{ Value : "DIN", Condition : [{FD:"D"} ]}},
        {Body:{ Value : "Aluminum", Condition : [{BT:"1"} ]}},{Trim:{ Value : "Aluminum", Condition : [{BT:"1"} ]}},
        {Body:{ Value : "Aluminum", Condition : [{BT:"2"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"2"} ]}},
        {Body:{ Value : "Carbon Steel", Condition : [{BT:"3"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"3"} ]}},
        {Body:{ Value : "316 SST", Condition : [{BT:"4"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"4"} ]}},
        {Body:{ Value : "Ductile Iron", Condition : [{BT:"5"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"5"} ]}},
        {TrimCoating:{ Value : "None", Condition : [{TC:"0"} ]}},
        {TrimCoating:{ Value : "All Weather Coating", Condition : [{TC:"1"} ]}},
        {Insert:{ Value : "Teflon®", Condition : [{IN:"T"} ]}},
        {Insert:{ Value : "Buna-N", Condition : [{IN:"B"} ]}},
        {Insert:{ Value : "Viton®", Condition : [{IN:"V"} ]}},
        {Gaskets:{ Value : "Fiber", Condition : [{GK:"O"} ]}},{O_ring:{ Value : "Buna-N", Condition : [{GK:"O"} ]}},
        {Gaskets:{ Value : "Teflon®", Condition : [{GK:"T"} ]}},{O_ring:{ Value : "Teflon®", Condition : [{GK:"T"} ]}},
        {Gaskets:{ Value : "Buna-N", Condition : [{GK:"B"} ]}},{O_ring:{ Value : "Buna-N", Condition : [{GK:"B"} ]}},
        {Gaskets:{ Value : "Viton®", Condition : [{GK:"V"} ]}},{O_ring:{ Value : "Viton®", Condition : [{GK:"V"} ]}},
        {Screen:{ Value : "Plastic", Condition : [{SR:"P"} ]}},{Retainer:{ Value : "Plastic", Condition : [{SR:"P"} ]}},
        {Screen:{ Value : "304 SST", Condition : [{SR:"S"} ]}},{Retainer:{ Value : "316 SST", Condition : [{SR:"S"} ]}},
        {VacuumRange:{ Value : "Low Vacuum Setting", Condition : [{RG:"02"} ]}},
        {VacuumRange:{ Value : "High Vacuum Setting", Condition : [{RG:"04"} ]}}
        
        ]},
        {ModelId:"3650B", Data :[
        {ValveType:{ Value : "Weight Loaded Tank Vent - In Line", Condition : [{ST1:"365"} ]}},{Screen:{ Value : "N/A", Condition : [{ST1:"365"} ]}},{Retainer:{ Value : "N/A", Condition : [{ST1:"365"} ]}},{Spring:{ Value : "N/A", Condition : [{ST1:"365"} ]}},
        {InletSize:{ Value : "2", Condition : [{SZ:"2"} ]}},{OutletSize:{ Value : "3", Condition : [{SZ:"2"} ]}},
        {InletSize:{ Value : "3", Condition : [{SZ:"3"} ]}},{OutletSize:{ Value : "4", Condition : [{SZ:"3"} ]}},
        {InletSize:{ Value : "4", Condition : [{SZ:"4"} ]}},{OutletSize:{ Value : "6", Condition : [{SZ:"4"} ]}},
        {InletSize:{ Value : "6", Condition : [{SZ:"6"} ]}},{OutletSize:{ Value : "8", Condition : [{SZ:"6"} ]}},
        {InletSize:{ Value : "8", Condition : [{SZ:"8"} ]}},{OutletSize:{ Value : "10", Condition : [{SZ:"8"} ]}},
        {InletSize:{ Value : "10", Condition : [{SZ:"0"} ]}},{OutletSize:{ Value : "12", Condition : [{SZ:"0"} ]}},
        {InletSize:{ Value : "12", Condition : [{SZ:"1"} ]}},{OutletSize:{ Value : "14", Condition : [{SZ:"1"} ]}},
        {InletConn:{ Value : "FF", Condition : [{FF:"F"} ]}},{OutletConn:{ Value : "FF", Condition : [{FF:"F"} ]}},
        {InletConn:{ Value : "RF", Condition : [{FF:"R"} ]}},{OutletConn:{ Value : "RF", Condition : [{FF:"R"} ]}},
        {InletRating:{ Value : "150#", Condition : [{FD:"F"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{FD:"F"} ]}},{OutletRating:{ Value : "150#", Condition : [{FD:"F"} ]}},{OutletFinish:{ Value : "Drilling", Condition : [{FD:"F"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{FD:"F"} ]}},
        {InletRating:{ Value : "PN16", Condition : [{FD:"D"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{FD:"D"} ]}},{OutletRating:{ Value : "PN16", Condition : [{FD:"D"} ]}},{OutletFinish:{ Value : "Drilling", Condition : [{FD:"D"} ]}},{Standard:{ Value : "DIN", Condition : [{FD:"D"} ]}},
        {Body:{ Value : "Aluminum", Condition : [{BT:"1"} ]}},{Trim:{ Value : "Aluminum", Condition : [{BT:"1"} ]}},
        {Body:{ Value : "Aluminum", Condition : [{BT:"2"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"2"} ]}},
        {Body:{ Value : "Carbon Steel", Condition : [{BT:"3"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"3"} ]}},
        {Body:{ Value : "316 SST", Condition : [{BT:"4"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"4"} ]}},
        {Body:{ Value : "Ductile Iron", Condition : [{BT:"5"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"5"} ]}},
        {TrimCoating:{ Value : "None", Condition : [{TC:"0"} ]}},
        {TrimCoating:{ Value : "All Weather Coating", Condition : [{TC:"1"} ]}},
        {Insert:{ Value : "Teflon®", Condition : [{IN:"T"} ]}},
        {Insert:{ Value : "Buna-N", Condition : [{IN:"B"} ]}},
        {Insert:{ Value : "Viton®", Condition : [{IN:"V"} ]}},
        {Gaskets:{ Value : "Fiber", Condition : [{GK:"O"} ]}},{O_ring:{ Value : "Buna-N", Condition : [{GK:"O"} ]}},
        {Gaskets:{ Value : "Teflon®", Condition : [{GK:"T"} ]}},{O_ring:{ Value : "Teflon®", Condition : [{GK:"T"} ]}},
        {Gaskets:{ Value : "Buna-N", Condition : [{GK:"B"} ]}},{O_ring:{ Value : "Buna-N", Condition : [{GK:"B"} ]}},
        {Gaskets:{ Value : "Viton®", Condition : [{GK:"V"} ]}},{O_ring:{ Value : "Viton®", Condition : [{GK:"V"} ]}},
        {PressureRange:{ Value : "Low Pressure Setting", Condition : [{RG:"02"},{PSERV:"P"} ]}},{VacuumRange:{ Value : "N/A", Condition : [{RG:"02"},{PSERV:"P"} ]}},
        {PressureRange:{ Value : "N/A", Condition : [{RG:"02"},{PSERV:"V"} ]}},{VacuumRange:{ Value : "Low Vacuum Setting", Condition : [{RG:"02"},{PSERV:"V"} ]}},
        {PressureRange:{ Value : "High Pressure Setting", Condition : [{RG:"04"},{PSERV:"P"} ]}},{VacuumRange:{ Value : "N/A", Condition : [{RG:"04"},{PSERV:"P"} ]}},
        {PressureRange:{ Value : "N/A", Condition : [{RG:"04"},{PSERV:"V"} ]}},{VacuumRange:{ Value : "High Vacuum Setting", Condition : [{RG:"04"},{PSERV:"V"} ]}}
        
        ]},
        {ModelId:"7100B", Data :[
        {ValveType:{ Value : "Weight Loaded Tank Vent - Vent To Atm.", Condition : [{ST1:"710"} ]}},{VacuumRange:{ Value : "N/A", Condition : [{ST1:"710"} ]}},{Spring:{ Value : "N/A", Condition : [{ST1:"710"} ]}},
        {InletSize:{ Value : "2", Condition : [{SZ:"2"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"2"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"2"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"2"} ]}},
        {InletSize:{ Value : "3", Condition : [{SZ:"3"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"3"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"3"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"3"} ]}},
        {InletSize:{ Value : "4", Condition : [{SZ:"4"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"4"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"4"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"4"} ]}},
        {InletSize:{ Value : "6", Condition : [{SZ:"6"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"6"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"6"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"6"} ]}},
        {InletSize:{ Value : "8", Condition : [{SZ:"8"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"8"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"8"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"8"} ]}},
        {InletSize:{ Value : "10", Condition : [{SZ:"0"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"0"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"0"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"0"} ]}},
        {InletSize:{ Value : "12", Condition : [{SZ:"1"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"1"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"1"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"1"} ]}},
        {InletConn:{ Value : "FF", Condition : [{FF:"F"} ]}},
        {InletConn:{ Value : "RF", Condition : [{FF:"R"} ]}},
        {InletRating:{ Value : "150#", Condition : [{FD:"F"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{FD:"F"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{FD:"F"} ]}},
        {InletRating:{ Value : "PN16", Condition : [{FD:"D"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{FD:"D"} ]}},{Standard:{ Value : "DIN", Condition : [{FD:"D"} ]}},
        {Body:{ Value : "Aluminum", Condition : [{BT:"1"} ]}},{Trim:{ Value : "Aluminum", Condition : [{BT:"1"} ]}},
        {Body:{ Value : "Aluminum", Condition : [{BT:"2"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"2"} ]}},
        {Body:{ Value : "Carbon Steel", Condition : [{BT:"3"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"3"} ]}},
        {Body:{ Value : "316 SST", Condition : [{BT:"4"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"4"} ]}},
        {Body:{ Value : "Ductile Iron", Condition : [{BT:"5"} ]}},{Trim:{ Value : "316 SST", Condition : [{BT:"5"} ]}},
        {TrimCoating:{ Value : "None", Condition : [{TC:"0"} ]}},
        {TrimCoating:{ Value : "All Weather Coating", Condition : [{TC:"1"} ]}},
        {Insert:{ Value : "Teflon®", Condition : [{IN:"T"} ]}},
        {Insert:{ Value : "Buna-N", Condition : [{IN:"B"} ]}},
        {Insert:{ Value : "Viton®", Condition : [{IN:"V"} ]}},
        {Gaskets:{ Value : "Fiber", Condition : [{GK:"O"} ]}},{O_ring:{ Value : "Buna-N", Condition : [{GK:"O"} ]}},
        {Gaskets:{ Value : "Teflon®", Condition : [{GK:"T"} ]}},{O_ring:{ Value : "Teflon®", Condition : [{GK:"T"} ]}},
        {Gaskets:{ Value : "Buna-N", Condition : [{GK:"B"} ]}},{O_ring:{ Value : "Buna-N", Condition : [{GK:"B"} ]}},
        {Gaskets:{ Value : "Viton®", Condition : [{GK:"V"} ]}},{O_ring:{ Value : "Viton®", Condition : [{GK:"V"} ]}},
        {Screen:{ Value : "Plastic", Condition : [{SR:"P"} ]}},{Retainer:{ Value : "Plastic", Condition : [{SR:"P"} ]}},
        {Screen:{ Value : "304 SST", Condition : [{SR:"S"} ]}},{Retainer:{ Value : "316 SST", Condition : [{SR:"S"} ]}},
        {PressureRange:{ Value : "Low Pressure Setting", Condition : [{RG:"02"} ]}},
        {PressureRange:{ Value : "High Pressure Setting", Condition : [{RG:"04"} ]}}
        ]},
        {ModelId:"221P", Data :[
        {ValveType:{ Value : "Emergency Pressure Relief Manway Cover", Condition : [{ST1:"221"} ]}},
        {InletSize:{ Value : "18", Condition : [{SZ:"18"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"18"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"18"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"18"} ]}},
        {InletSize:{ Value : "20", Condition : [{SZ:"20"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"20"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"20"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"20"} ]}},
        {InletSize:{ Value : "24", Condition : [{SZ:"24"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"24"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"24"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"24"} ]}},
        {InletRating:{ Value : "Standard", Condition : [{SZ:"18"},{BD:"1"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{SZ:"18"},{BD:"1"} ]}},
        {InletRating:{ Value : "API 650", Condition : [{SZ:"20"},{BD:"1"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{SZ:"20"},{BD:"1"} ]}},
        {InletRating:{ Value : "API 650", Condition : [{SZ:"24"},{BD:"1"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{SZ:"24"},{BD:"1"} ]}},
        {InletConn:{ Value : "FF", Condition : [{BD:"2"} ]}},{InletRating:{ Value : "150#", Condition : [{BD:"2"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{BD:"2"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{BD:"2"} ]}},
        {Base:{ Value : "Carbon Steel", Condition : [{BC:"1"} ]}},{Cover:{ Value : "Aluminum", Condition : [{BC:"1"} ]}},
        {Base:{ Value : "Aluminum", Condition : [{BC:"2"} ]}},{Cover:{ Value : "Aluminum", Condition : [{BC:"2"} ]}},
        {Base:{ Value : "Carbon Steel", Condition : [{BC:"3"} ]}},{Cover:{ Value : "Carbon Steel", Condition : [{BC:"3"} ]}},
        {Base:{ Value : "316 SST", Condition : [{BC:"4"} ]}},{Cover:{ Value : "316 SST", Condition : [{BC:"4"} ]}},
        {Diaphragm:{ Value : "Buna-N", Condition : [{SE:"B"} ]}},{Pad:{ Value : "Neoprene", Condition : [{SE:"B"} ]}},
        {Diaphragm:{ Value : "Teflon®", Condition : [{SE:"T"} ]}},{Pad:{ Value : "Neoprene", Condition : [{SE:"T"} ]}},
        {Diaphragm:{ Value : "Viton®", Condition : [{SE:"V"} ]}},{Pad:{ Value : "Viton®", Condition : [{SE:"V"} ]}}
        ]},
        {ModelId:"221PV", Data:[
        {ValveType:{ Value : "Emergency Pressure Relief Manway Cover", Condition : [{ST1:"221"} ]}},
        {InletSize:{ Value : "18", Condition : [{SZ:"18"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"18"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"18"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"18"} ]}},
        {InletSize:{ Value : "20", Condition : [{SZ:"20"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"20"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"20"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"20"} ]}},
        {InletSize:{ Value : "24", Condition : [{SZ:"24"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"24"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"24"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"24"} ]}},
        {InletRating:{ Value : "Standard", Condition : [{SZ:"18"},{BD:"1"} ]}},
        {InletRating:{ Value : "API 650", Condition : [{SZ:"20"},{BD:"1"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{SZ:"20"},{BD:"1"} ]}},
        {InletRating:{ Value : "API 650", Condition : [{SZ:"24"},{BD:"1"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{SZ:"24"},{BD:"1"} ]}},
        {InletConn:{ Value : "FF", Condition : [{BD:"2"} ]}},{InletRating:{ Value : "150#", Condition : [{BD:"2"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{BD:"2"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{BD:"2"} ]}},
        {Base:{ Value : "Carbon Steel", Condition : [{BC:"1"} ]}},{Cover:{ Value : "Aluminum", Condition : [{BC:"1"} ]}},
        {Base:{ Value : "Aluminum", Condition : [{BC:"2"} ]}},{Cover:{ Value : "Aluminum", Condition : [{BC:"2"} ]}},
        {Base:{ Value : "Carbon Steel", Condition : [{BC:"3"} ]}},{Cover:{ Value : "Carbon Steel", Condition : [{BC:"3"} ]}},
        {Base:{ Value : "316 SST", Condition : [{BC:"4"} ]}},{Cover:{ Value : "316 SST", Condition : [{BC:"4"} ]}},
        {Diaphragm:{ Value : "Buna-N", Condition : [{SE:"B"} ]}},{Pad:{ Value : "Neoprene", Condition : [{SE:"B"} ]}},
        {Diaphragm:{ Value : "Teflon®", Condition : [{SE:"T"} ]}},{Pad:{ Value : "Neoprene", Condition : [{SE:"T"} ]}},
        {Diaphragm:{ Value : "Viton®", Condition : [{SE:"V"} ]}},{Pad:{ Value : "Viton®", Condition : [{SE:"V"} ]}}
        ]},
        {ModelId:"711", Data:[
        {ValveType:{ Value : "Spring Loaded Tank Vent - Vent To Atm.", Condition : [{ST:"711"} ]}},{GuideTube:{ Value : "None", Condition : [{ST:"711"} ]}},{SeatPlate:{ Value : "N/A", Condition : [{ST:"711"} ]}},{Seat:{ Value : "BUNA-N", Condition : [{ST:"711"} ]}},
        {InletSize:{ Value : "2", Condition : [{SZ:"02"} ]}},{InletRating:{ Value : "150#", Condition : [{SZ:"02"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{SZ:"02"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"02"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"02"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"02"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{SZ:"02"} ]}},
        {InletSize:{ Value : "3", Condition : [{SZ:"03"} ]}},{InletRating:{ Value : "150#", Condition : [{SZ:"03"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{SZ:"03"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"03"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"03"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"03"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{SZ:"03"} ]}},
        {InletSize:{ Value : "4", Condition : [{SZ:"04"} ]}},{InletRating:{ Value : "150#", Condition : [{SZ:"04"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{SZ:"04"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"04"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"04"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"04"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{SZ:"04"} ]}},
        {InletSize:{ Value : "6", Condition : [{SZ:"06"} ]}},{InletRating:{ Value : "150#", Condition : [{SZ:"06"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{SZ:"06"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"06"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"06"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"06"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{SZ:"06"} ]}},
        {InletSize:{ Value : "8", Condition : [{SZ:"08"} ]}},{InletRating:{ Value : "150#", Condition : [{SZ:"08"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{SZ:"08"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"08"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"08"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"08"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{SZ:"08"} ]}},
        {InletSize:{ Value : "10", Condition : [{SZ:"10"} ]}},{InletRating:{ Value : "150#", Condition : [{SZ:"10"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{SZ:"10"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"10"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"10"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"10"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{SZ:"10"} ]}},
        {InletSize:{ Value : "12", Condition : [{SZ:"12"} ]}},{InletRating:{ Value : "150#", Condition : [{SZ:"12"} ]}},{InletFinish:{ Value : "Drilling", Condition : [{SZ:"12"} ]}},{OutletSize:{ Value : "Vent", Condition : [{SZ:"12"} ]}},{OutletConn:{ Value : "To", Condition : [{SZ:"12"} ]}},{OutletRating:{ Value : "Atm.", Condition : [{SZ:"12"} ]}},{Standard:{ Value : "ANSI B16.5", Condition : [{SZ:"12"} ]}},
        {InletConn:{ Value : "FF", Condition : [{BT:"11"} ]}},{Body:{ Value : "Aluminum", Condition : [{BT:"11"} ]}},{SeatRing:{ Value : "Aluminum", Condition : [{BT:"11"} ]}},{InletScreen:{ Value : "Plastic", Condition : [{BT:"11"} ]}},{SeatRingRetainer:{ Value : "Plastic", Condition : [{BT:"11"} ]}},{FlangeCap:{ Value : "Zinc Plated Carbon Steel", Condition : [{BT:"11"} ]}},
        {InletConn:{ Value : "FF", Condition : [{BT:"16"} ]}},{Body:{ Value : "Aluminum", Condition : [{BT:"16"} ]}},{SeatRing:{ Value : "316 SST", Condition : [{BT:"16"} ]}},{InletScreen:{ Value : "304 SST", Condition : [{BT:"16"} ]}},{SeatRingRetainer:{ Value : "316 SST", Condition : [{BT:"16"} ]}},{FlangeCap:{ Value : "Zinc Plated Carbon Steel", Condition : [{BT:"16"} ]}},
        {InletConn:{ Value : "RF", Condition : [{BT:"36"} ]}},{Body:{ Value : "Carbon Steel", Condition : [{BT:"36"} ]}},{SeatRing:{ Value : "316 SST", Condition : [{BT:"36"} ]}},{InletScreen:{ Value : "304 SST", Condition : [{BT:"36"} ]}},{SeatRingRetainer:{ Value : "316 SST", Condition : [{BT:"36"} ]}},{FlangeCap:{ Value : "Zinc Plated Carbon Steel", Condition : [{BT:"36"} ]}},
        {InletConn:{ Value : "RF", Condition : [{BT:"66"} ]}},{Body:{ Value : "316SST", Condition : [{BT:"66"} ]}},{SeatRing:{ Value : "316 SST", Condition : [{BT:"66"} ]}},{InletScreen:{ Value : "304 SST", Condition : [{BT:"66"} ]}},{SeatRingRetainer:{ Value : "316 SST", Condition : [{BT:"66"} ]}},{FlangeCap:{ Value : "Stainless Steel", Condition : [{BT:"66"} ]}},
        {GuideRod:{ Value : "Metal to Metal (No Insert)", Condition : [{IN:"M"} ]}},
        {GuideRod:{ Value : "BUNA-N", Condition : [{IN:"B"} ]}},
        {GuideRod:{ Value : "Teflon®", Condition : [{IN:"T"} ]}},
        {GuideRod:{ Value : "Viton®", Condition : [{IN:"V"} ]}},
        {RetainerBolts:{ Value : "Spring Range A", Condition : [{RG:"A"} ]}},{PressureReliefConnectionSize:{ Value : "N/A", Condition : [{RG:"A"} ]}},
        {RetainerBolts:{ Value : "Spring Range B", Condition : [{RG:"B"} ]}},{PressureReliefConnectionSize:{ Value : "N/A", Condition : [{RG:"B"} ]}},
        {RetainerBolts:{ Value : "Spring Range C", Condition : [{RG:"C"} ]}},{PressureReliefConnectionSize:{ Value : "N/A", Condition : [{RG:"C"} ]}},
        {RetainerBolts:{ Value : "Spring Range D", Condition : [{RG:"D"} ]}},{PressureReliefConnectionSize:{ Value : "N/A", Condition : [{RG:"D"} ]}},
        {RetainerBolts:{ Value : "Spring Range E", Condition : [{RG:"E"} ]}},{PressureReliefConnectionSize:{ Value : "N/A", Condition : [{RG:"E"} ]}},
        {RetainerBolts:{ Value : "Spring Range F", Condition : [{RG:"F"} ]}},{PressureReliefConnectionSize:{ Value : "N/A", Condition : [{RG:"F"} ]}},
        {RetainerBolts:{ Value : "Spring Range G", Condition : [{RG:"G"} ]}},{PressureReliefConnectionSize:{ Value : "N/A", Condition : [{RG:"G"} ]}},
        {RetainerBolts:{ Value : "Spring Range H", Condition : [{RG:"H"} ]}},{PressureReliefConnectionSize:{ Value : "N/A", Condition : [{RG:"H"} ]}}
        ]}
]

module.exports = {
    tankVent
}