export const preferenceData={

    status:"success",
    data:{
        "preference": [
            {
                "Id": "1",
                "Section Name": "Preference",
                "Display Order for section": "1",
                "DisplayOrder": "1",
                "Name": "DisplayUnitSystem",
                "Description": "Display Unit System",
                "Label": "dropdown",
                "Type": "yes",
                "IsMandatory": "no",
                "IsDisabled": "All",
                "AutoFill": "NULL",
                "DimentionName": "DisplayUnits",
                "LOV": "NULL",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "2",
                "Section Name": "Preference",
                "Display Order for section": "1",
                "DisplayOrder": "2",
                "Name": "CalculationMethod",
                "Description": "Calculation Method",
                "Label": "dropdown",
                "Type": "yes",
                "IsMandatory": "no",
                "IsDisabled": "English",
                "AutoFill": "NULL",
                "DimentionName": "Calculation Method",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "3",
                "Section Name": "System Properties",
                "Display Order for section": "2",
                "DisplayOrder": "1",
                "Name": "SystemAtmPressure",
                "Description": "Atm. Pressure",
                "Label": "inputuom",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "14.696",
                "AutoFill": "abspressure",
                "DimentionName": "NULL",
                "LOV": "Display Unit System",
                "Dependency ": "TRUE",
                "NeedValidation": "NULL",
                "Clarifications": "0",
                "MinLength": "NA",
                "MaxLength": "ATM. Pressure [Patm]",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "4",
                "Section Name": "System Properties",
                "Display Order for section": "2",
                "DisplayOrder": "2",
                "Name": "SystemPressure",
                "Description": "Pressure",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "pressure",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "5",
                "Section Name": "System Properties",
                "Display Order for section": "2",
                "DisplayOrder": "3",
                "Name": "SystemTemperature",
                "Description": "Temperature",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "temperature",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "6",
                "Section Name": "Fluid Properties",
                "Display Order for section": "3",
                "DisplayOrder": "1",
                "Name": "FluidLiquidViscosity",
                "Description": "Liquid Viscosity",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "viscosity, viscositykin",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "7",
                "Section Name": "Fluid Properties",
                "Display Order for section": "3",
                "DisplayOrder": "2",
                "Name": "FluidSpecificHeat",
                "Description": "Specific Heat",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "specificheat",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "8",
                "Section Name": "Fluid Properties",
                "Display Order for section": "3",
                "DisplayOrder": "3",
                "Name": "FluidMassFlux",
                "Description": "Mass Flux",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "massflux",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "It is not dependent on display unit in desktop app",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "9",
                "Section Name": "Fluid Properties",
                "Display Order for section": "3",
                "DisplayOrder": "4",
                "Name": "FluidSpecificVolume",
                "Description": "Specific Volume",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "specificvolume",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "10",
                "Section Name": "Fluid Properties",
                "Display Order for section": "3",
                "DisplayOrder": "5",
                "Name": "FluidLatentHeat",
                "Description": "Latent Heat of Vaporization",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "latentheat",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "11",
                "Section Name": "Fluid Properties",
                "Display Order for section": "3",
                "DisplayOrder": "6",
                "Name": "FluidDensity",
                "Description": "Density",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "density",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "12",
                "Section Name": "Fluid Properties",
                "Display Order for section": "3",
                "DisplayOrder": "7",
                "Name": "FluidHeatInput",
                "Description": "Heat Input",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "power",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "It is not dependent on display unit in desktop app",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "13",
                "Section Name": "Flowrate Properties",
                "Display Order for section": "4",
                "DisplayOrder": "1",
                "Name": "FlowrateGas",
                "Description": "Gas",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "massflow, gasvolflow, gasvolflowact",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "14",
                "Section Name": "Flowrate Properties",
                "Display Order for section": "4",
                "DisplayOrder": "2",
                "Name": "FlowrateAPI521Fire",
                "Description": "API 521 Fire",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "gasvolflowact",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "15",
                "Section Name": "Flowrate Properties",
                "Display Order for section": "4",
                "DisplayOrder": "3",
                "Name": "FlowrateSubcooled",
                "Description": "Subcooled (2-Phase)",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "massflow, liquidvolflow",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "16",
                "Section Name": "Flowrate Properties",
                "Display Order for section": "4",
                "DisplayOrder": "4",
                "Name": "FlowrateLiquid",
                "Description": "Liquid ",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "massflow, liquidvolflow/",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "17",
                "Section Name": "Flowrate Properties",
                "Display Order for section": "4",
                "DisplayOrder": "5",
                "Name": "Flowrate2Phase",
                "Description": "2-Phase",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "massflow",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "18",
                "Section Name": "Flowrate Properties",
                "Display Order for section": "4",
                "DisplayOrder": "6",
                "Name": "FlowrateTankBlanketRegulator",
                "Description": "Tank Blanket Regulator",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "gasvolflow, gasvolflowact",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "19",
                "Section Name": "Flowrate Properties",
                "Display Order for section": "4",
                "DisplayOrder": "7",
                "Name": "FlowrateSteam",
                "Description": "Steam",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "massflow",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "20",
                "Section Name": "Valve Properties",
                "Display Order for section": "5",
                "DisplayOrder": "1",
                "Name": "ValveDataSetSinglePhase",
                "Description": "Data Set ( Single Phase )",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "ASME",
                "AutoFill": "NULL",
                "DimentionName": "datasetforvalve",
                "LOV": "NULL",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "21",
                "Section Name": "Valve Properties",
                "Display Order for section": "5",
                "DisplayOrder": "2",
                "Name": "ValveDataSetMultiPhase",
                "Description": "Data Set ( Multi Phase ) ",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "ASME",
                "AutoFill": "NULL",
                "DimentionName": "datasetforvalve",
                "LOV": "NULL",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "22",
                "Section Name": "Valve Properties",
                "Display Order for section": "5",
                "DisplayOrder": "3",
                "Name": "ValveOrificArea",
                "Description": "Orifice Area",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "area",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "23",
                "Section Name": "Valve Properties",
                "Display Order for section": "5",
                "DisplayOrder": "4",
                "Name": "ValveReactionForce",
                "Description": "Reaction Force ",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "force",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "24",
                "Section Name": "Valve Properties",
                "Display Order for section": "5",
                "DisplayOrder": "5",
                "Name": "ValveDimention",
                "Description": "Dimension",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "lengthforvalve",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "25",
                "Section Name": "Valve Properties",
                "Display Order for section": "5",
                "DisplayOrder": "6",
                "Name": "ValveWeight",
                "Description": "Weight ",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "mass",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "26",
                "Section Name": "Valve Properties",
                "Display Order for section": "5",
                "DisplayOrder": "7",
                "Name": "ValveDistanceFromValve",
                "Description": "Distance from Valve",
                "Label": "inputuom",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "NULL",
                "AutoFill": "length",
                "DimentionName": "NULL",
                "LOV": "Display Unit System",
                "Dependency ": "TRUE",
                "NeedValidation": "NULL",
                "Clarifications": "0",
                "MinLength": "NA",
                "MaxLength": "Distance from Valve [r]",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "27",
                "Section Name": "Vessel Properties",
                "Display Order for section": "6",
                "DisplayOrder": "1",
                "Name": "VesselDimentions",
                "Description": "Dimensions",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "length",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "28",
                "Section Name": "Vessel Properties",
                "Display Order for section": "6",
                "DisplayOrder": "2",
                "Name": "VesselSurfaceArea",
                "Description": "Surface Area",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "area",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "29",
                "Section Name": "Vessel Properties",
                "Display Order for section": "6",
                "DisplayOrder": "3",
                "Name": "VesselVolume",
                "Description": "Volume",
                "Label": "dropdown",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "No Default",
                "AutoFill": "NULL",
                "DimentionName": "volume",
                "LOV": "Display Unit System",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "30",
                "Section Name": "General Settings",
                "Display Order for section": "7",
                "DisplayOrder": "1",
                "Name": "GeneralEnable7thEditionfor2Phase",
                "Description": "Enable 7th Edition for 2-Phase",
                "Label": "checkbox",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "NULL",
                "AutoFill": "NULL",
                "DimentionName": "NULL",
                "LOV": "NULL",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            },
            {
                "Id": "31",
                "Section Name": "General Settings",
                "Display Order for section": "7",
                "DisplayOrder": "2",
                "Name": "GeneralEnable6thEditionfor2Phase",
                "Description": "Enable 6th Edition for 2-Phase",
                "Label": "checkbox",
                "Type": "no",
                "IsMandatory": "no",
                "IsDisabled": "NULL",
                "AutoFill": "NULL",
                "DimentionName": "NULL",
                "LOV": "NULL",
                "Dependency ": "FALSE",
                "NeedValidation": "NULL",
                "Clarifications": "NA",
                "MinLength": "NA",
                "MaxLength": "NULL",
                "Tooltip": "Preferences",
                "ReferenceTable": "NULL",
                "FieldGroupType": "NULL",
                "FieldGroupName": "NULL"
            }
        ]
    }
}