const flowKey = [
  {
    product_type: "Pressure Relief",
    service_type: "Gas/Vapor",
    code: "Non-Code (API 2000, 7th Edition)",
    is_section_VIII: null,
    service: "P",
    ka_dataset: "Any",
    req_dimension_name: "massflow",
    Display_Flow_Set1: "WmaxP",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Gas/Vapor",
    code: "Non-Code (API 2000, 7th Edition)",
    is_section_VIII: null,
    service: "P",
    ka_dataset: "Any",
    req_dimension_name: "volFlow",
    Display_Flow_Set1: "VmaxP",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Gas/Vapor",
    code: "Non-Code (API 2000, 7th Edition)",
    is_section_VIII: null,
    service: "V",
    ka_dataset: "Any",
    req_dimension_name: "massflow",
    Display_Flow_Set1: "WmaxV",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Gas/Vapor",
    code: "Non-Code (API 2000, 7th Edition)",
    is_section_VIII: null,
    service: "V",
    ka_dataset: "Any",
    req_dimension_name: "volFlow",
    Display_Flow_Set1: "VmaxV",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Tank Vent",
    service_type: "Tank Vent",
    code: "Pressure Relief Valve (API 2000, 7th Edition)",
    is_section_VIII: null,
    service: "P",
    ka_dataset: "Any",
    req_dimension_name: "massflow",
    Display_Flow_Set1: "WmaxP",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Tank Vent",
    service_type: "Tank Vent",
    code: "Pressure Relief Valve (API 2000, 7th Edition)",
    is_section_VIII: null,
    service: "P",
    ka_dataset: "Any",
    req_dimension_name: "volFlow",
    Display_Flow_Set1: "VmaxP",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Tank Vent",
    service_type: "Tank Vent",
    code: "Pressure Relief Valve (API 2000, 7th Edition)",
    is_section_VIII: null,
    service: "V",
    ka_dataset: "Any",
    req_dimension_name: "massflow",
    Display_Flow_Set1: "WmaxV",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Tank Vent",
    service_type: "Tank Vent",
    code: "Pressure Relief Valve (API 2000, 7th Edition)",
    is_section_VIII: null,
    service: "V",
    ka_dataset: "Any",
    req_dimension_name: "volFlow",
    Display_Flow_Set1: "VmaxV",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Flame Arrester",
    service_type: "Flame Arrester",
    code: "Flame Arrester (VAREC)",
    is_section_VIII: null,
    service: "P",
    ka_dataset: "Any",
    req_dimension_name: "massflow",
    Display_Flow_Set1: "WmaxP",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Flame Arrester",
    service_type: "Flame Arrester",
    code: "Flame Arrester (VAREC)",
    is_section_VIII: null,
    service: "P",
    ka_dataset: "Any",
    req_dimension_name: "volFlow",
    Display_Flow_Set1: "VmaxP",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Flame Arrester",
    service_type: "Flame Arrester",
    code: "Flame Arrester (VAREC)",
    is_section_VIII: null,
    service: "V",
    ka_dataset: "Any",
    req_dimension_name: "massflow",
    Display_Flow_Set1: "WmaxV",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Flame Arrester",
    service_type: "Flame Arrester",
    code: "Flame Arrester (VAREC)",
    is_section_VIII: null,
    service: "V",
    ka_dataset: "Any",
    req_dimension_name: "volFlow",
    Display_Flow_Set1: "VmaxV",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Tank Vent",
    service_type: "Tank Vent",
    code: "Free Vent (API 2000, 7th Edition)",
    is_section_VIII: null,
    service: "P",
    ka_dataset: "Any",
    req_dimension_name: "massflow",
    Display_Flow_Set1: "WmaxP",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Tank Vent",
    service_type: "Tank Vent",
    code: "Free Vent (API 2000, 7th Edition)",
    is_section_VIII: null,
    service: "P",
    ka_dataset: "Any",
    req_dimension_name: "volFlow",
    Display_Flow_Set1: "VmaxP",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Tank Vent",
    service_type: "Tank Vent",
    code: "Free Vent (API 2000, 7th Edition)",
    is_section_VIII: null,
    service: "V",
    ka_dataset: "Any",
    req_dimension_name: "massflow",
    Display_Flow_Set1: "WmaxV",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Tank Vent",
    service_type: "Tank Vent",
    code: "Free Vent (API 2000, 7th Edition)",
    is_section_VIII: null,
    service: "V",
    ka_dataset: "Any",
    req_dimension_name: "volFlow",
    Display_Flow_Set1: "VmaxV",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Gas/Vapor",
    code: "ASME Section VIII/XIII - UV (API 520, Part I, 10th Edition)",
    is_section_VIII: "unchecked",
    service: "PV",
    ka_dataset: "ASME",
    req_dimension_name: "massflow",
    Display_Flow_Set1: "wact",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Gas/Vapor",
    code: "ASME Section VIII/XIII - UV (API 520, Part I, 10th Edition)",
    is_section_VIII: "unchecked",
    service: "PV",
    ka_dataset: "ASME",
    req_dimension_name: "volFlow",
    Display_Flow_Set1: "vact",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Gas/Vapor",
    code: "ASME Section VIII/XIII - UV (API 520, Part I, 10th Edition)",
    is_section_VIII: null,
    service: "PV",
    ka_dataset: "API",
    req_dimension_name: "massflow",
    Display_Flow_Set1: "WmaxP",
    Display_Kx_Set1: "K,api",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Gas/Vapor",
    code: "ASME Section VIII/XIII - UV (API 520, Part I, 10th Edition)",
    is_section_VIII: null,
    service: "PV",
    ka_dataset: "API",
    req_dimension_name: "volFlow",
    Display_Flow_Set1: "VmaxP",
    Display_Kx_Set1: "K,api",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Gas/Vapor",
    code: "Non-Code (API 520, Part 1, 10th Edition)",
    is_section_VIII: null,
    service: "PV",
    ka_dataset: "ASME",
    req_dimension_name: "massflow",
    Display_Flow_Set1: "wact",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Gas/Vapor",
    code: "Non-Code (API 520, Part 1, 10th Edition)",
    is_section_VIII: null,
    service: "PV",
    ka_dataset: "ASME",
    req_dimension_name: "Any",
    Display_Flow_Set1: "vact",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Gas/Vapor",
    code: "Non-Code (API 520, Part 1, 10th Edition)",
    is_section_VIII: null,
    service: "PV",
    ka_dataset: "API",
    req_dimension_name: "massflow",
    Display_Flow_Set1: "WmaxP",
    Display_Kx_Set1: "K,api",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Gas/Vapor",
    code: "Non-Code (API 520, Part 1, 10th Edition)",
    is_section_VIII: null,
    service: "PV",
    ka_dataset: "API",
    req_dimension_name: "volFlow",
    Display_Flow_Set1: "VmaxP",
    Display_Kx_Set1: "K,api",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Gas/Vapor",
    code: "ISO 4126-7 (2nd Edition)",
    is_section_VIII: null,
    service: "PV",
    ka_dataset: "any",
    req_dimension_name: "Any",
    Display_Flow_Set1: "qm",
    Display_Kx_Set1: "Kdr",
    Display_Flow_Set2: "Qmact",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Gas/Vapor",
    code: "ASME Section VIII/XIII - UV (API 520, Part I, 10th Edition)",
    is_section_VIII: "true",
    service: "PV",
    ka_dataset: "ASME",
    req_dimension_name: "massflow",
    Display_Flow_Set1: "wrtd",
    Display_Kx_Set1: "K",
    Display_Flow_Set2: "wact",
    Display_Kx_Set2: "Kd",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Gas/Vapor",
    code: "ASME Section VIII/XIII - UV (API 520, Part I, 10th Edition)",
    is_section_VIII: "true",
    service: "PV",
    ka_dataset: "ASME",
    req_dimension_name: "volFlow",
    Display_Flow_Set1: "vrtd",
    Display_Kx_Set1: "K",
    Display_Flow_Set2: "vact",
    Display_Kx_Set2: "Kd",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Liquid",
    code: "ASME Section VIII/XIII - UV (API 520, Part I, 10th Edition)",
    is_section_VIII: "true",
    service: "PV",
    ka_dataset: "ASME",
    req_dimension_name: "Any",
    Display_Flow_Set1: "vrtd",
    Display_Kx_Set1: "K",
    Display_Flow_Set2: "vact",
    Display_Kx_Set2: "Kd",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Liquid",
    code: "ASME Section VIII/XIII - UV (API 520, Part I, 10th Edition)",
    is_section_VIII: null,
    service: "PV",
    ka_dataset: "API",
    req_dimension_name: "Any",
    Display_Flow_Set1: "VmaxP",
    Display_Kx_Set1: "K,api",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Liquid",
    code: "ASME Section VIII/XIII - UV (API 520, Part I, 10th Edition)",
    is_section_VIII: "unchecked",
    service: "PV",
    ka_dataset: "ASME",
    req_dimension_name: "Any",
    Display_Flow_Set1: "vact",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Liquid",
    code: "Non-Code (API 520, Part 1, 10th Edition)",
    is_section_VIII: null,
    service: "PV",
    ka_dataset: "ASME",
    req_dimension_name: "Any",
    Display_Flow_Set1: "vact",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Liquid",
    code: "Non-Code (API 520, Part 1, 10th Edition)",
    is_section_VIII: null,
    service: "PV",
    ka_dataset: "API",
    req_dimension_name: "Any",
    Display_Flow_Set1: "VmaxP",
    Display_Kx_Set1: "K,api",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Liquid",
    code: "ISO 4126-7 (2nd Edition)",
    is_section_VIII: null,
    service: "PV",
    ka_dataset: "Any",
    req_dimension_name: "Any",
    Display_Flow_Set1: "qm",
    Display_Kx_Set1: "Kdr",
    Display_Flow_Set2: "Qmact",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Steam",
    code: "ASME Section VIII/XIII - UV (API 520, Part I, 10th Edition)",
    is_section_VIII: "true",
    service: "PV",
    ka_dataset: "ASME",
    req_dimension_name: "Any",
    Display_Flow_Set1: "wrtd",
    Display_Kx_Set1: "K",
    Display_Flow_Set2: "wact",
    Display_Kx_Set2: "Kd",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Steam",
    code: "ASME Section VIII/XIII - UV (API 520, Part I, 10th Edition)",
    is_section_VIII: null,
    service: "PV",
    ka_dataset: "API",
    req_dimension_name: "Any",
    Display_Flow_Set1: "WmaxP",
    Display_Kx_Set1: "K,api",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Steam",
    code: "ASME Section VIII/XIII - UV (API 520, Part I, 10th Edition)",
    is_section_VIII: "unchecked",
    service: "PV",
    ka_dataset: "ASME",
    req_dimension_name: "Any",
    Display_Flow_Set1: "wact",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Steam",
    code: "Non-Code (API 520, Part 1, 10th Edition)",
    is_section_VIII: null,
    service: "PV",
    ka_dataset: "ASME",
    req_dimension_name: "Any",
    Display_Flow_Set1: "wact",
    Display_Kx_Set1: "Kd",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Steam",
    code: "Non-Code (API 520, Part 1, 10th Edition)",
    is_section_VIII: null,
    service: "PV",
    ka_dataset: "API",
    req_dimension_name: "Any",
    Display_Flow_Set1: "WmaxP",
    Display_Kx_Set1: "K,api",
    Display_Flow_Set2: "",
    Display_Kx_Set2: "",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Steam",
    code: "ASME Section I - V",
    is_section_VIII: null,
    service: "PV",
    ka_dataset: "Any",
    req_dimension_name: "Any",
    Display_Flow_Set1: "wrtd",
    Display_Kx_Set1: "K",
    Display_Flow_Set2: "wact",
    Display_Kx_Set2: "Kd",
  },
  {
    product_type: "Pressure Relief",
    service_type: "Steam",
    code: "ISO 4126-7 (2nd Edition)",
    is_section_VIII: null,
    service: "PV",
    ka_dataset: "Any",
    req_dimension_name: "Any",
    Display_Flow_Set1: "qm",
    Display_Kx_Set1: "Kdr",
    Display_Flow_Set2: "Qmact",
    Display_Kx_Set2: "",
  },
];

//req_dimension_name(any) -> anything other than massflow //
//is_section_VIII(any)-> not applicable
const filterFlowKey = (sizingData) => {
  const req_dimension_name = sizingData.req_pressure_flow_uom.includes("mass")
    ? "massflow"
    : sizingData.req_pressure_flow_uom.includes("vol")
    ? "volFlow"
    : "Any";
  const service =
    sizingData.service === "P" ? "P" : sizingData.service === "V" ? "V" : "PV";
  let result = flowKey.filter(
    (e) =>
      e["product_type"] === sizingData["product_type"] &&
      e["service_type"] === sizingData["service_type"] &&
      e["code"] === sizingData["code"] &&
      e["is_section_VIII"] === sizingData.is_section_VIII &&
      e["service"].includes(service) &&
      (e["ka_dataset"] === "Any"
        ? e["ka_dataset"] != sizingData.k_a_dataset
        : e["ka_dataset"] === sizingData.k_a_dataset) &&
      (e["req_dimension_name"] === "Any"
        ? e["req_dimension_name"] != req_dimension_name
        : e["req_dimension_name"] === req_dimension_name)
  );
  console.log("result----flowkey------", result);
  return result;
};

module.exports = { filterFlowKey };
