let venting_String = [
    ["Normal Venting - 7th Ed., Annex A - Pressure & Vacuum",
    "Normal Venting - 7th Ed., Annex A - Pressure Only",
    "Normal Venting - 7th Ed., Annex A - Vacuum Only"],
    ["Normal Venting - 7th Ed., Main - Pressure & Vacuum",
    "Normal Venting - 7th Ed., Main - Pressure Only",
    "Normal Venting - 7th Ed., Main - Vacuum Only"],
    ["Emergency Venting - 7th Ed., Annex A"],
    ["Emergency Venting - 7th Ed., Main"],
    ["Emergency Venting & Normal Vaccum - 7th Ed., Annex A"],
    ["Emergency Venting & Normal Vaccum - 7th Ed., Main"],
    ["Emergency Venting - 7th Ed., Annex A",
    "Emergency Venting - 7th Ed., Main"],
    ["Normal Venting - 7th Ed., Annex A - Pressure & Vacuum", //7
      "Normal Venting - 7th Ed., Annex A - Pressure Only",
      "Normal Venting - 7th Ed., Annex A - Vacuum Only",
      "Normal Venting - 7th Ed., Main - Pressure & Vacuum",
      "Normal Venting - 7th Ed., Main - Pressure Only",
      "Normal Venting - 7th Ed., Main - Vacuum Only",
      "Emergency Venting & Normal Vaccum - 7th Ed., Annex A",
      "Emergency Venting & Normal Vaccum - 7th Ed., Main",
      ],
      ["Normal Venting - 7th Ed., Annex A - Pressure & Vacuum",
      "Normal Venting - 7th Ed., Annex A - Pressure Only"],
      ["Normal Venting - 7th Ed., Annex A - Pressure & Vacuum",
        "Normal Venting - 7th Ed., Annex A - Vacuum Only",
        "Emergency Venting & Normal Vaccum - 7th Ed., Annex A"
        ],
        ["Emergency Venting - 7th Ed., Annex A",
          "Emergency Venting - 7th Ed., Main",
          "Emergency Venting & Normal Vaccum - 7th Ed., Annex A",
          "Emergency Venting & Normal Vaccum - 7th Ed., Main",
          ],
          ["Normal Venting - 7th Ed., Main - Pressure & Vacuum",
            "Normal Venting - 7th Ed., Main - Pressure Only",
            "Normal Venting - 7th Ed., Main - Vacuum Only",
            "Emergency Venting & Normal Vaccum - 7th Ed., Main"
          ],
          ["Normal Venting - 7th Ed., Main - Pressure & Vacuum",
            "Normal Venting - 7th Ed., Main - Pressure Only"
          ],
          ["Normal Venting - 7th Ed., Main - Pressure & Vacuum",
            "Normal Venting - 7th Ed., Main - Vacuum Only",
            "Emergency Venting & Normal Vaccum - 7th Ed., Main"
            ]
  ];
  
const subSummary_conditions = [
    {
      subSummary: venting_String[0],
      subTemplateId: 207,
      templateId: 41,
    },
    {
      subSummary: venting_String[1],
      subTemplateId: 208,
      templateId: 41,
    },
    {
      subSummary: venting_String[2],
      subTemplateId: 209,
      templateId: 41,
    },
    {
      subSummary: venting_String[3],
      subTemplateId: 210,
      templateId: 41,
    },
    {
      subSummary: venting_String[4],
      subTemplateId: 211,
      templateId: 41,
    },
    {
      subSummary: venting_String[5],
      subTemplateId: 212,
      templateId: 41,
    },
  ];
  
const subInput_conditions = [
    {
      subInput: venting_String[0],
      subTemplateId: 213,
      templateId: 41,
    },
    {
      subInput: venting_String[6],
      subTemplateId: 214,
      templateId: 41,
    },
    {
      subInput: venting_String[1],
      subTemplateId: 215,
      templateId: 41,
    },
    {
      subInput: venting_String[4],
      subTemplateId: 216,
      templateId: 41,
    },
    {
      subInput: venting_String[5],
      subTemplateId: 217,
      templateId: 41,
    },
  ];
  
  
const subEquation_conditions = [
    // templateid 41
    //subEq 1
    {
      firstLevelConditions: venting_String[7],
      secondLevelConditions: [{
        tank_shape: "Spherical",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 219,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String[8],
      secondLevelConditions: [{
        tank_shape: "Cylindrical (Horizontal or Vertical) with Flat ends",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 220,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String[9],
      secondLevelConditions: [{
        tank_shape: "Cylindrical (Horizontal or Vertical) with Hemispherical",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 221,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String[10],
      secondLevelConditions: [{
        tank_shape: "Rectangular (Horizontal or Vertical)",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 222,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String[10],
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 223,
      templateId: 41,
    },
    //subEq 2
    { //EQ8=>sys_mawp=MAWP
      firstLevelConditions: venting_String[11],
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "English",
        flash_point: 'sizingData["flash_point"] >= 100',
        boiling_point: 'sizingData["boiling_point"] >= 300',
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 224,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String[11],
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "English",
        flash_point: 'sizingData["flash_point"] < 100',
        boiling_point: 'sizingData["boiling_point"] < 300',
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 225,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String[12],
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "Metric",
        flash_point: 'sizingData["flash_point"] >= 100',
        boiling_point: 'sizingData["boiling_point"] >= 300',
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 226,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String[13],
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "Metric",
        flash_point: 'sizingData["flash_point"] < 100',
        boiling_point: 'sizingData["boiling_point"] < 300',
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 227,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 228,
      templateId: 41,
    },
    //subEq 3
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "English",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 229,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "Metric",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 230,
      templateId: 41,
    },
    {
      //User Defined Vacuum Flow
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 231,
      templateId: 41,
    },
    //subEq 4
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 232,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 233,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 234,
      templateId: 41,
    },
    {
      //eq:3.9 nt fnd
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 235,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "set_pressure<15",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 236,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 237,
      templateId: 41,
    },
    {
      // eq:3.12 nt fnd
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 238,
      templateId: 41,
    },
    {
      // eq:3.13 nt fnd
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 239,
      templateId: 41,
    },
    {
      // User Defined
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 240,
      templateId: 41,
    },
    //subEq 5 //2nd cond
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        Wetted_Surface_Area: 'sizingData["Wetted_Surface_Area"] >= 100',
        //////Design_Pressure: 'sizingData["Design Pressure"] <= 15>',
        MAWP: "NA",
        AWET: 'sizingData["AWET"] <= 2800>',
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 241,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "English",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        Wetted_Surface_Area: 'sizingData["Wetted_Surface_Area"] >= 2800',
        //////Design_Pressure: '1 < sizingData["Design Pressure"] < 15',
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 242,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "Metric",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        Wetted_Surface_Area: 'sizingData["Wetted_Surface_Area"] >= 260',
        //////Design_Pressure: '0.07 < sizingData["Design Pressure"] < 1.034',
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 243,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        Wetted_Surface_Area: "Wetted Surface Area < 200",
        //////Design_Pressure: "NA",
        MAWP: "MAWP(psig) ≤ 15",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 244,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        Wetted_Surface_Area:
          "WettedSurfaceArea(ft2) ≥ 200 && WettedSurfaceArea(ft2) < 1000",
        //////Design_Pressure: "NA",
        MAWP: "MAWP(psig) ≤ 15",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 245,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        Wetted_Surface_Area:
          "WettedSurfaceArea(ft2) ≥ 1000 && WettedSurfaceArea(ft2) < 2800",
        //////Design_Pressure: "NA",
        MAWP: "MAWP(psig) ≤ 15",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 246,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        Wetted_Surface_Area: "WettedSurfaceArea(ft2) ≥ 2800",
        //////Design_Pressure: "NA",
        MAWP: "1 <= MAWP(psig) <= 15",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 247,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        Wetted_Surface_Area: "WettedSurfaceArea(ft2) ≥ 2800",
        //////Design_Pressure: "NA",
        MAWP: "MAWP(psig) ≤ 1",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 248,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        Wetted_Surface_Area: "WettedSurfaceArea(m2) < 18.6",
        //////Design_Pressure: "NA",
        MAWP: "MAWP(barg) ≤ 1.034",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 249,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        Wetted_Surface_Area:
          "WettedSurfaceArea(m2) ≥ 18.6 && WettedSurfaceArea(m2)< 93",
        //////Design_Pressure: "NA",
        MAWP: "MAWP(barg) ≤ 1.034",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 250,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        Wetted_Surface_Area:
          "WettedSurfaceArea(ft2) ≥ 1000 && WettedSurfaceArea(ft2) < 2800",
        //////Design_Pressure: "NA",
        MAWP: "MAWP(psig) ≤ 15",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 251,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        Wetted_Surface_Area: "WettedSurfaceArea(ft2) ≥ 2800",
        //////Design_Pressure: "NA",
        MAWP: '1 <= sizingData["sys_mawp"] <= 15',
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 252,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        Wetted_Surface_Area: "WettedSurfaceArea(ft2) ≥ 2800",
        //////Design_Pressure: "NA",
        MAWP: "MAWP(psig) <= 1",
        // AWET: "NA",
        HeatInput: "14090000",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 253,
      templateId: 41,
    },
    {
      //User Defined Emergency Flow
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        //////Design_Pressure: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 254,
      templateId: 41,
    },
    //subEq 6
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "Spherical",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        //////Design_Pressure: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 255,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "Cylindrical (Horizontal or Vertical) with Flat ends",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        //////Design_Pressure: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 256,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "Cylindrical Vessel with Hemispherical Ends",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        //////Design_Pressure: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 257,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "Rectangular Vessel",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        //////Design_Pressure: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 258,
      templateId: 41,
    },
    {
      //User Defined
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        //////Design_Pressure: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 259,
      templateId: 41,
    },
    //subEq 7
    {
      //Equation 3.29 nt fnd
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        //////Design_Pressure: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 260,
      templateId: 41,
    },
    {
      //Equation 3.30 nt fnd
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        //////Design_Pressure: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 261,
      templateId: 41,
    },
    {
      //Equation 3.33 nt fnd
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        //////Design_Pressure: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 262,
      templateId: 41,
    },
    {
      //No Insulation
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "NA",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        //////Design_Pressure: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 263,
      templateId: 41,
    },
    //subEq 8
    //Tn =>normal_operating
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "English",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "normal_operating ≤ 120°F",
        product_in_tank: "Nonvolatile",
      }],
      subTemplateId: 264,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "Metric",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "normal_operating ≤ 49°C",
        product_in_tank: "Nonvolatile",
      }],
      subTemplateId: 265,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "English",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "normal_operating > 120°F",
        product_in_tank: "Nonvolatile",
      }],
      subTemplateId: 266,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "Metric",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "normal_operating > 120°F",
        product_in_tank: "Nonvolatile",
      }],
      subTemplateId: 267,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "English",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "normal_operating ≤ 120°F",
        product_in_tank: "Volatile",
      }],
      subTemplateId: 268,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "Metric",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "normal_operating ≤ 49°C",
        product_in_tank: "Volatile",
      }],
      subTemplateId: 269,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "English",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "normal_operating > 120°F",
        product_in_tank: "Volatile",
      }],
      subTemplateId: 270,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "Metric",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "normal_operating > 120°F",
        product_in_tank: "Volatile",
      }],
      subTemplateId: 271,
      templateId: 41,
    },
    {
      //User Defined Pressure Flow
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "Metric",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 272,
      templateId: 41,
    },
    //subEq 9
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "English",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 273,
      templateId: 41,
    },
    {
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "Metric",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 274,
      templateId: 41,
    },
    {
      //User Defined Vacuum Flow
      firstLevelConditions: venting_String,
      secondLevelConditions: [{
        tank_shape: "NA",
        prefCalculationMethod: "Metric",
        flash_point: "NA",
        boiling_point: "NA",
        set_pressure: "NA",
        // Wetted_Surface_Area: "NA",
        MAWP: "NA",
        // AWET: "NA",
        // HeatInput: "NA",
        normal_operating: "NA",
        product_in_tank: "NA",
      }],
      subTemplateId: 275,
      templateId: 41,
    },
  ];
  
  // export const TankType_conditions =[
  //   {
  
  //     subTemplateId: 218,
  //     templateId: 41,
  //     }
  //   ]
  
module.exports = { 
    subSummary_conditions,
    subInput_conditions,
    subEquation_conditions
};