module.exports = {
    default: [
        { key: "setPressure", lookupKey: "PMG_SP", defaultValue: "" },
        { key: "setPressureUOM", lookupKey: "PMG_UOM_PRESS", defaultValue: "" },
        // { key: "modelNumber", lookupKey: "SizingModel", defaultValue: "", location: 'parent' },
        { key: "modelNumber", lookupKey: "PMG_CATALOG_NUMBER", defaultValue: "" },
        { key: "catalogString", lookupKey: "PMG_CATALOG_NUMBER", defaultValue: "" },
        { key: "lastModified", lookupKey: "ChangedOn", defaultValue: null, location: 'parent' },
        { key: "quantity", lookupKey: "PMG_QUANTITY", defaultValue: "1" }
    ],
    AG_400_FB: [
        { key: "Notes", lookupKey: "notes", defaultValue: "", source: "ui" },
        { key: "NAME1", lookupKey: "NAME1", defaultValue: "", source: "ui" },
        { key: "ZZPROJN", lookupKey: "projectName", defaultValue: "", source: "ui" },
        { key: "BSTNK", lookupKey: "poNumber", defaultValue: "", source: "ui" },
        { key: "Z106", lookupKey: "serialNumber", defaultValue: "", source: "ui" },
        { key: "Z102", lookupKey: "tagNumber", defaultValue: "", source: "ui" },
        { key: "Title", lookupKey: "title", defaultValue: "", source: "ui" },
        { key: "VBELN-POSNR", lookupKey: "assemblyNo", defaultValue: "", source: "ui" },
        { key: "VBELN", lookupKey: "salesOrder", defaultValue: "", source: "ui" },
        { key: "Requested_By", lookupKey: "requestedBy", defaultValue: "", source: "ui" },
        { key: "VIN", lookupKey: "vin", defaultValue: "", source: "ui" },
        { key: "LOC", lookupKey: "location", defaultValue: "STA", source: "ui" },
        { key: "LANG", lookupKey: "language", defaultValue: "ENG", source: "ui" },
        { key: "Model_Number", lookupKey: "PMG_CATALOG_NUMBER", defaultValue: "", location: 'parent' },
        { key: "Set_Pressure", lookupKey: "PMG_SP", defaultValue: "" },
        { key: "Set_Pressure_UOM", lookupKey: "PMG_UOM_PRESS", defaultValue: "" },
        { key: "PMG_MODEL", lookupKey: "PMG_MODEL", defaultValue: "" },
        { key: "BLK", lookupKey: "AG_400_FB_BLK", defaultValue: "" },
        { key: "CC", lookupKey: "AG_400_FB_CC", defaultValue: "" },
        { key: "CODE", lookupKey: "PMG_CODE", defaultValue: "" },
        { key: "FC", lookupKey: "PMG_FC", defaultValue: "" },
        { key: "FT", lookupKey: "AG_400_FB_FT", defaultValue: "" },
        { key: "IC", lookupKey: "AG_400_FB_IC", defaultValue: "" },
        { key: "ICFS", lookupKey: "AG_400_FB_ICFS", defaultValue: "" },
        { key: "MAT", lookupKey: "AG_400_FB_MAT", defaultValue: "" },
        { key: "MOD", lookupKey: "AG_400_FB_MOD", defaultValue: "" },
        { key: "MVBT", lookupKey: "AG_400_FB_MVBT", defaultValue: "" },
        { key: "MVL", lookupKey: "AG_400_FB_MVL", defaultValue: "" },
        { key: "MVPT", lookupKey: "AG_400_FB_MVPT", defaultValue: "" },
        { key: "MVS", lookupKey: "AG_400_FB_MVS", defaultValue: "" },
        { key: "MVSG", lookupKey: "AG_400_FB_MVSG", defaultValue: "" },
        { key: "N", lookupKey: "AG_400_FB_N", defaultValue: "" },
        { key: "OC", lookupKey: "AG_400_FB_OC", defaultValue: "" },
        { key: "OR", lookupKey: "AG_400_FB_OR", defaultValue: "" },
        { key: "PGA", lookupKey: "AG_400_FB_PGA", defaultValue: "" },
        { key: "PSG", lookupKey: "AG_400_FB_PSG", defaultValue: "" },
        { key: "SERV", lookupKey: "AG_400_FB_SERV", defaultValue: "" },
        { key: "VS", lookupKey: "AG_400_FB_VS", defaultValue: "" },
        { key: "VMD", lookupKey: "AG_400_FB_VMD", defaultValue: "G" },
        { key: "VMD", lookupKey: "AG_400_FB_VMD", defaultValue: "J" },
        { key: "ACC1", lookupKey: "AG_400_FB_ACC1", defaultValue: "" },
        { key: "ACC2", lookupKey: "AG_400_FB_ACC2", defaultValue: "" },
        { key: "ACC3", lookupKey: "AG_400_FB_ACC3", defaultValue: "" },
        { key: "ACC4", lookupKey: "AG_400_FB_ACC4", defaultValue: "" },
        { key: "ACC5", lookupKey: "AG_400_FB_ACC5", defaultValue: "" },
        { key: "ACC6", lookupKey: "AG_400_FB_ACC6", defaultValue: "" },
        { key: "ACC7", lookupKey: "AG_400_FB_ACC7", defaultValue: "" },
        { key: "ACC8", lookupKey: "AG_400_FB_ACC8", defaultValue: "" },
        { key: "ACC9", lookupKey: "AG_400_FB_ACC9", defaultValue: "" },
        { key: "ACC10", lookupKey: "AG_400_FB_ACC10", defaultValue: "" },
        { key: "PSP", lookupKey: "AG_400_FB_PSP", defaultValue: "" },
        { key: "SPR", lookupKey: "AG_400_FB_SPR", defaultValue: "" },
        { key: "PE", lookupKey: "AG_400_FB_PE", defaultValue: "" },
        { key: "SPLDOC", lookupKey: "PMG_SPEC_RQMT_STDDOC", defaultValue: "" },
        { key: "DNU_Tag_Name", lookupKey: "DNU_Tag_Name", defaultValue: "hpp" },
        { key: "DNU_Tag_Guid", lookupKey: "DNU_Tag_Guid", defaultValue: "" },
        { key: "DNU_Tag_Company", lookupKey: "DNU_Tag_Company", defaultValue: "" },
        { key: "DNU_Tag_Project", lookupKey: "DNU_Tag_Project", defaultValue: "" },
        { key: "DNU_Tag_Quantity", lookupKey: "DNU_Tag_Quantity", defaultValue: "" },
        { key: "DNU_PRV2SIZE_ModelNumber", lookupKey: "SizingModel", defaultValue: "", location: 'parent' }
        // {key: "DNU_PRV2SIZE_Version", lookupKey: "DNU_PRV2SIZE_Version", defaultValue: "pr7_20210922.1"},
        // {key: "DNU_PRV2SIZE_Config_Version", lookupKey: "DNU_PRV2SIZE_Config_Version", defaultValue: "ODWvjoNbHFF6LwwU6jTZXV4gonMnBlxhd/ZrddR2uv0="},
    ],
    CR_OMNI: [
        { key: "Notes", lookupKey: "notes", defaultValue: "", source: "ui" },
        { key: "NAME1", lookupKey: "NAME1", defaultValue: "", source: "ui" },
        { key: "ZZPROJN", lookupKey: "projectName", defaultValue: "", source: "ui" },
        { key: "BSTNK", lookupKey: "poNumber", defaultValue: "", source: "ui" },
        { key: "Z106", lookupKey: "serialNumber", defaultValue: "", source: "ui" },
        { key: "Z102", lookupKey: "tagNumber", defaultValue: "Omni", source: "ui" },
        { key: "Title", lookupKey: "title", defaultValue: "", source: "ui" },
        { key: "VBELN-POSNR", lookupKey: "assemblyNo", defaultValue: "", source: "ui" },
        { key: "VBELN", lookupKey: "salesOrder", defaultValue: "", source: "ui" },
        { key: "Requested_By", lookupKey: "requestedBy", defaultValue: "", source: "ui" },
        { key: "VIN", lookupKey: "vin", defaultValue: "", source: "ui" },
        { key: "LOC", lookupKey: "location", defaultValue: "STA", source: "ui" },
        { key: "LANG", lookupKey: "language", defaultValue: "ENG", source: "ui" },
        { key: "Model_Number", lookupKey: "PMG_CATALOG_NUMBER", defaultValue: "", location: 'parent' },
        { key: "Set_Pressure", lookupKey: "PMG_SP", defaultValue: "" },
        { key: "Set_Pressure_UOM", lookupKey: "PMG_UOM_PRESS", defaultValue: "" },
        { key: "PMG_MODEL", lookupKey: "PMG_MODEL", defaultValue: "CR_OMNI" },
        { key: "BD", lookupKey: "CR_OMNI_BD", defaultValue: "" },
        { key: "BLK", lookupKey: "CR_OMNI_BLK", defaultValue: "" },
        { key: "BT", lookupKey: "CR_OMNI_BT", defaultValue: "" },
        { key: "CC", lookupKey: "CR_OMNI_CC", defaultValue: "" },
        { key: "CODE", lookupKey: "PMG_CODE", defaultValue: "" },
        { key: "CS", lookupKey: "CR_OMNI_CS", defaultValue: "" },
        { key: "CT", lookupKey: "CR_OMNI_CT", defaultValue: "" },
        { key: "FC", lookupKey: "PMG_FC", defaultValue: "" },
        { key: "FF", lookupKey: "CR_OMNI_FF", defaultValue: "" },
        { key: "MD", lookupKey: "CR_OMNI_MD", defaultValue: "" },
        { key: "NC", lookupKey: "CR_OMNI_NC", defaultValue: "" },
        { key: "NU", lookupKey: "CR_OMNI_NU", defaultValue: "" },
        { key: "PT", lookupKey: "CR_OMNI_PT", defaultValue: "" },
        { key: "SM", lookupKey: "CR_OMNI_SM", defaultValue: "" },
        { key: "VMD", lookupKey: "CR_OMNI_VMD", defaultValue: "" },
        { key: "VC", lookupKey: "CR_OMNI_VC", defaultValue: "" },
        { key: "VS", lookupKey: "CR_OMNI_VS", defaultValue: "" },
        { key: "CM", lookupKey: "CR_OMNI_CM", defaultValue: "" },
        { key: "PR", lookupKey: "CR_OMNI_PR", defaultValue: "" },
        { key: "SGPR", lookupKey: "CR_OMNI_SGPR", defaultValue: "" },
        { key: "TR", lookupKey: "CR_OMNI_TR", defaultValue: "" },
        { key: "GrpMD", lookupKey: "CR_OMNI_GRPMD", defaultValue: "" },
        { key: "GrpSM1", lookupKey: "CR_OMNI_GRPSM1", defaultValue: "" },
        { key: "GrpSM2", lookupKey: "CR_OMNI_GRPSM2", defaultValue: "" },
        { key: "SPLDOC", lookupKey: "PMG_SPEC_RQMT_STDDOC", defaultValue: "" },
        { key: "CLEAN", lookupKey: "PMG_SPEC_RQMT_CLEAN", defaultValue: "" },
        { key: "COO", lookupKey: "PMG_SPEC_RQMT_COO", defaultValue: "" },
        { key: "DNU_Tag_Name", lookupKey: "DNU_Tag_Name", defaultValue: "Omni" },
        { key: "DNU_Tag_Guid", lookupKey: "DNU_Tag_Guid", defaultValue: "" },
        { key: "DNU_Tag_Company", lookupKey: "DNU_Tag_Company", defaultValue: "" },
        { key: "DNU_Tag_Project", lookupKey: "DNU_Tag_Project", defaultValue: "" },
        { key: "DNU_Tag_Quantity", lookupKey: "DNU_Tag_Quantity", defaultValue: "" },
        { key: "DNU_PRV2SIZE_ModelNumber", lookupKey: "SizingModel", defaultValue: "", location: 'parent' }
    ],
    AG_200_API: [
        { key: "Notes", lookupKey: "notes", defaultValue: "", source: "ui" },
        { key: "NAME1", lookupKey: "NAME1", defaultValue: "", source: "ui" },
        { key: "ZZPROJN", lookupKey: "projectName", defaultValue: "", source: "ui" },
        { key: "BSTNK", lookupKey: "poNumber", defaultValue: "", source: "ui" },
        { key: "Z106", lookupKey: "serialNumber", defaultValue: "", source: "ui" },
        { key: "Z102", lookupKey: "tagNumber", defaultValue: "Omni", source: "ui" },
        { key: "Title", lookupKey: "title", defaultValue: "", source: "ui" },
        { key: "VBELN-POSNR", lookupKey: "assemblyNo", defaultValue: "", source: "ui" },
        { key: "VBELN", lookupKey: "salesOrder", defaultValue: "", source: "ui" },
        { key: "Requested_By", lookupKey: "requestedBy", defaultValue: "", source: "ui" },
        { key: "VIN", lookupKey: "vin", defaultValue: "", source: "ui" },
        { key: "LOC", lookupKey: "location", defaultValue: "STA", source: "ui" },
        { key: "LANG", lookupKey: "language", defaultValue: "ENG", source: "ui" },
        { key: "Model_Number", lookupKey: "PMG_CATALOG_NUMBER", defaultValue: "", location: 'parent' },
        { key: "Set_Pressure", lookupKey: "PMG_SP", defaultValue: "" },
        { key: "Set_Pressure_UOM", lookupKey: "PMG_UOM_PRESS", defaultValue: "" },
        { key: "PMG_MODEL", lookupKey: "PMG_MODEL", defaultValue: "AG_200_API" },
        { key: "BLK", lookupKey: "AG_200_API_BLK", defaultValue: "" },
        { key: "CC", lookupKey: "AG_200_API_CC", defaultValue: "" },
        { key: "CODE", lookupKey: "PMG_CODE", defaultValue: "" },
        { key: "FC", lookupKey: "PMG_FC", defaultValue: "" },
        { key: "FT", lookupKey: "AG_200_API_FT", defaultValue: "" },
        { key: "IC", lookupKey: "AG_200_API_IC", defaultValue: "" },
        { key: "ICFS", lookupKey: "AG_200_API_ICFS", defaultValue: "" },
        { key: "MAT", lookupKey: "AG_200_API_MAT", defaultValue: "" },
        { key: "MOD", lookupKey: "AG_200_API_MOD", defaultValue: "" },
        { key: "MVBT", lookupKey: "AG_200_API_MVBT", defaultValue: "" },
        { key: "MVL", lookupKey: "AG_200_API_MVL", defaultValue: "" },
        { key: "MVPT", lookupKey: "AG_200_API_MVPT", defaultValue: "" },
        { key: "MVS", lookupKey: "AG_200_API_MVS", defaultValue: "" },
        { key: "MVSG", lookupKey: "AG_200_API_MVSG", defaultValue: "" },
        { key: "N", lookupKey: "AG_200_API_N", defaultValue: "" },
        { key: "OC", lookupKey: "AG_200_API_OC", defaultValue: "" },
        { key: "OR", lookupKey: "AG_200_API_OR", defaultValue: "" },
        { key: "PSG", lookupKey: "AG_200_API_PSG", defaultValue: "" },
        { key: "SERV", lookupKey: "AG_200_API_SERV", defaultValue: "" },
        { key: "VS", lookupKey: "AG_200_API_VS", defaultValue: "" },
        { key: "VMD", lookupKey: "AG_200_API_VMD", defaultValue: "" },
        { key: "ACC1", lookupKey: "AG_200_API_ACC1", defaultValue: "" },
        { key: "ACC2", lookupKey: "AG_200_API_ACC2", defaultValue: "" },
        { key: "ACC3", lookupKey: "AG_200_API_ACC3", defaultValue: "" },
        { key: "ACC4", lookupKey: "AG_200_API_ACC4", defaultValue: "" },
        { key: "ACC5", lookupKey: "AG_200_API_ACC5", defaultValue: "" },
        { key: "ACC6", lookupKey: "AG_200_API_ACC6", defaultValue: "" },
        { key: "ACC7", lookupKey: "AG_200_API_ACC7", defaultValue: "" },
        { key: "ACC8", lookupKey: "AG_200_API_ACC8", defaultValue: "" },
        { key: "ACC9", lookupKey: "AG_200_API_ACC9", defaultValue: "" },
        { key: "PSP", lookupKey: "AG_200_API_PSP", defaultValue: "" },
        { key: "SPR", lookupKey: "AG_200_API_SPR", defaultValue: "" },
        { key: "PE", lookupKey: "AG_200_API_PE", defaultValue: "" },
        { key: "SPLDOC", lookupKey: "PMG_SPEC_RQMT_STDDOC", defaultValue: "" },
        { key: "DNU_Tag_Name", lookupKey: "DNU_Tag_Name", defaultValue: "200" },
        { key: "DNU_Tag_Guid", lookupKey: "DNU_Tag_Guid", defaultValue: "" },
        { key: "DNU_Tag_Company", lookupKey: "DNU_Tag_Company", defaultValue: "" },
        { key: "DNU_Tag_Project", lookupKey: "DNU_Tag_Project", defaultValue: "" },
        { key: "DNU_Tag_Quantity", lookupKey: "DNU_Tag_Quantity", defaultValue: "1" },
        { key: "DNU_PRV2SIZE_ModelNumber", lookupKey: "SizingModel", defaultValue: "", location: 'parent' }
    ],
    AG_500: [
        { key: "Notes", lookupKey: "notes", defaultValue: "", source: "ui" },
        { key: "NAME1", lookupKey: "NAME1", defaultValue: "", source: "ui" },
        { key: "ZZPROJN", lookupKey: "projectName", defaultValue: "", source: "ui" },
        { key: "BSTNK", lookupKey: "poNumber", defaultValue: "", source: "ui" },
        { key: "Z106", lookupKey: "serialNumber", defaultValue: "", source: "ui" },
        { key: "Z102", lookupKey: "tagNumber", defaultValue: "Omni", source: "ui" },
        { key: "Title", lookupKey: "title", defaultValue: "", source: "ui" },
        { key: "VBELN-POSNR", lookupKey: "assemblyNo", defaultValue: "", source: "ui" },
        { key: "VBELN", lookupKey: "salesOrder", defaultValue: "", source: "ui" },
        { key: "Requested_By", lookupKey: "requestedBy", defaultValue: "", source: "ui" },
        { key: "VIN", lookupKey: "vin", defaultValue: "", source: "ui" },
        { key: "LOC", lookupKey: "location", defaultValue: "STA", source: "ui" },
        { key: "LANG", lookupKey: "language", defaultValue: "ENG", source: "ui" },
        { key: "Model_Number", lookupKey: "PMG_CATALOG_NUMBER", defaultValue: "", location: 'parent' },
        { key: "Set_Pressure", lookupKey: "PMG_SP", defaultValue: "" },
        { key: "Set_Pressure_UOM", lookupKey: "PMG_UOM_PRESS", defaultValue: "" },
        { key: "PMG_MODEL", lookupKey: "PMG_MODEL", defaultValue: "AG_500" },
        { key: "CC", lookupKey: "AG_500_CC", defaultValue: "" },
        { key: "CODE", lookupKey: "PMG_CODE", defaultValue: "" },
        { key: "FC", lookupKey: "PMG_FC", defaultValue: "" },
        { key: "FT", lookupKey: "AG_500_FT", defaultValue: "" },
        { key: "IFFS", lookupKey: "AG_500_IFFS", defaultValue: "" },
        { key: "MOD", lookupKey: "AG_500_MOD", defaultValue: "" },
        { key: "MVL", lookupKey: "AG_500_MVL", defaultValue: "" },
        { key: "OR", lookupKey: "AG_500_OR", defaultValue: "" },
        { key: "PSG", lookupKey: "AG_500_PSG", defaultValue: "" },
        { key: "VS", lookupKey: "AG_500_VS", defaultValue: "" },
        { key: "VMD", lookupKey: "AG_500_VMD", defaultValue: "" },
        { key: "ACC1", lookupKey: "AG_500_ACC1", defaultValue: "" },
        { key: "ACC2", lookupKey: "AG_500_ACC2", defaultValue: "" },
        { key: "ACC3", lookupKey: "AG_500_ACC3", defaultValue: "" },
        { key: "ACC4", lookupKey: "AG_500_ACC4", defaultValue: "" },
        { key: "ACC5", lookupKey: "AG_500_ACC5", defaultValue: "" },
        { key: "ACC6", lookupKey: "AG_500_ACC6", defaultValue: "" },
        { key: "ACC7", lookupKey: "AG_500_ACC7", defaultValue: "" },
        { key: "SPR", lookupKey: "AG_500_SPR", defaultValue: "" },
        { key: "PE", lookupKey: "AG_500_PE", defaultValue: "" },
        { key: "SPLDOC", lookupKey: "PMG_SPEC_RQMT_STDDOC", defaultValue: "" },
        { key: "DNU_Tag_Name", lookupKey: "DNU_Tag_Name", defaultValue: "500" },
        { key: "DNU_Tag_Guid", lookupKey: "DNU_Tag_Guid", defaultValue: "" },
        { key: "DNU_Tag_Company", lookupKey: "DNU_Tag_Company", defaultValue: "" },
        { key: "DNU_Tag_Project", lookupKey: "DNU_Tag_Project", defaultValue: "" },
        { key: "DNU_Tag_Quantity", lookupKey: "DNU_Tag_Quantity", defaultValue: "" },
        { key: "DNU_PRV2SIZE_ModelNumber", lookupKey: "SizingModel", defaultValue: "", location: 'parent' }
    ]
};
